### ISSUE TITLE
Cannot query reference sequence at....

### ISSUE THREAD

**Issue by cvlvxi** [Illumina/hap.py#101]
Hi there,

I'm trying to compare two vcfs and getting the following..

```
[W] overlapping records at chr1:26686335 for sample 0
[W] Variants that overlap on the reference allele: 247
[I] Total VCF records:         2504907
[I] Non-reference VCF records: 2504907
[W] overlapping records at chr1:26359844 for sample 0
[W] Variants that overlap on the reference allele: 244
[I] Total VCF records:         2617977
[I] Non-reference VCF records: 2617977
2019-10-21 13:46:27,286 ERROR    Preprocess command preprocess /tmp/tmpwD3Kpw.vcf.gz:* -l chr17:81485672-83115016 -o /tmp/input.chr17:81485672-83115016UFwTRE.prep.vcf.gz -V 1 -L 1 -r /misc/vcgs/seq/cpipe-2.3-prod/hg19.decoy/ucsc.hg19.with_decoy.fasta failed. Outputs are here /tmp/stdoutg9tpSs.log / /tmp/stderrLoNtHl.log
2019-10-21 13:46:27,287 ERROR    Cannot query reference sequence at :81499948-81499948
2019-10-21 13:46:27,287 ERROR    Exception when running <function preprocessWrapper at 0x7f7d3ac5ade8>:
2019-10-21 13:46:27,287 ERROR    ------------------------------------------------------------
2019-10-21 13:46:27,287 ERROR    Traceback (most recent call last):
2019-10-21 13:46:27,287 ERROR      File "/storage/chris/happy/hap.py-build/lib/python27/Tools/parallel.py", line 71, in parMapper
2019-10-21 13:46:27,288 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-10-21 13:46:27,288 ERROR      File "/storage/chris/happy/hap.py-build/lib/python27/Haplo/partialcredit.py", line 66, in preprocessWrapper
2019-10-21 13:46:27,288 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-10-21 13:46:27,288 ERROR      File "/storage/verification/VXF/tools/miniconda/lib/python2.7/subprocess.py", line 541, in check_call
2019-10-21 13:46:27,289 ERROR        raise CalledProcessError(retcode, cmd)
2019-10-21 13:46:27,289 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpwD3Kpw.vcf.gz:* -l chr17:81485672-83115016 -o /tmp/input.chr17:81485672-83115016UFwTRE.prep.vcf.gz -V 1 -L 1 -r /misc/vcgs/seq/cpipe-2.3-prod/hg19.decoy/ucsc.hg19.with_decoy.fasta' returned non-zero exit status 1
2019-10-21 13:46:27,289 ERROR    ------------------------------------------------------------
2019-10-21 13:46:29,331 ERROR    Preprocess command preprocess /tmp/tmpwD3Kpw.vcf.gz:* -l chr17:83115017-2147483647 -o /tmp/input.chr17:83115017-2147483647IjsRJQ.prep.vcf.gz -V 1 -L 1 -r /misc/vcgs/seq/cpipe-2.3-prod/hg19.decoy/ucsc.hg19.with_decoy.fasta failed. Outputs are here /tmp/stdoutYki7gL.log / /tmp/stderrcpfiO8.log
2019-10-21 13:46:29,332 ERROR    Cannot query reference sequence at :83217849-83217849
2019-10-21 13:46:29,332 ERROR    Exception when running <function preprocessWrapper at 0x7f7d3ac5ade8>:
2019-10-21 13:46:29,332 ERROR    ------------------------------------------------------------
2019-10-21 13:46:29,332 ERROR    Traceback (most recent call last):
2019-10-21 13:46:29,333 ERROR      File "/storage/chris/happy/hap.py-build/lib/python27/Tools/parallel.py", line 71, in parMapper
2019-10-21 13:46:29,333 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-10-21 13:46:29,333 ERROR      File "/storage/chris/happy/hap.py-build/lib/python27/Haplo/partialcredit.py", line 66, in preprocessWrapper
2019-10-21 13:46:29,333 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-10-21 13:46:29,333 ERROR      File "/storage/verification/VXF/tools/miniconda/lib/python2.7/subprocess.py", line 541, in check_call
2019-10-21 13:46:29,333 ERROR        raise CalledProcessError(retcode, cmd)
2019-10-21 13:46:29,333 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpwD3Kpw.vcf.gz:* -l chr17:83115017-2147483647 -o /tmp/input.chr17:83115017-2147483647IjsRJQ.prep.vcf.gz -V 1 -L 1 -r /misc/vcgs/seq/cpipe-2.3-prod/hg19.decoy/ucsc.hg19.with_decoy.fasta' returned non-zero exit status 1
2019-10-21 13:46:29,334 ERROR    ------------------------------------------------------------
2019-10-21 13:46:45,953 ERROR    Preprocess command preprocess /tmp/tmpwD3Kpw.vcf.gz:* -l chr18:75309292-79446520 -o /tmp/input.chr18:75309292-79446520jQRcqB.prep.vcf.gz -V 1 -L 1 -r /misc/vcgs/seq/cpipe-2.3-prod/hg19.decoy/ucsc.hg19.with_decoy.fasta failed. Outputs are here /tmp/stdoutspSjc6.log / /tmp/stderr5ebLMq.log
2019-10-21 13:46:45,954 ERROR    Cannot query reference sequence at :78971722-78971722
2019-10-21 13:46:45,954 ERROR    Exception when running <function preprocessWrapper at 0x7f7d3ac5ade8>:
2019-10-21 13:46:45,954 ERROR    ------------------------------------------------------------
2019-10-21 13:46:45,955 ERROR    Traceback (most recent call last):
```

I've tried using xcmp and vcfeval and get the same thing.. 

Any help would be appreciated.

**Comment by dskola** [comment]
Hi @cvlvxi ,

Can you post the command line you are using?

Do the chromosome names match between your query VCF, truth VCF and reference genome?
