### ISSUE TITLE
Issue with installation: ** No targets specified and no makefile found. Stop."

### ISSUE THREAD

**Issue by SonicNight** [Illumina/hap.py#108]
Upon running "python install.py ~/hap.py-install", I get the following error message:

-- Configuring incomplete, errors occurred!
See also "/tmp/buildMYGaCE/CMakeFiles/CMakeOutput.log".
cd /tmp/buildMYGaCE &&  make -j16
make: *** No targets specified and no makefile found.  Stop.
Traceback (most recent call last):
  File "install.py", line 298, in <module>
    main()
  File "install.py", line 283, in main
    build_haplotypes(source_dir, build_dir, args)
  File "install.py", line 157, in build_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/data/miniconda3/envs/python2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /tmp/buildMYGaCE &&  make -j16' returned non-zero exit status 2

**Comment by genespectrum** [comment]
I also have the same issue. Do you find the solution to solve this error?

**Comment by genespectrum** [comment]
install CMake and required packages that resolved the this error.
