### ISSUE TITLE
Error running BCFTOOLS

### ISSUE THREAD

**Issue by DBS-Max** [Illumina/hap.py#109]
I am getting the following error:

```
2020-02-13 22:21:21,214 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[W] overlapping records at chr1:20626004 for sample 0
[W] Variants that overlap on the reference allele: 109
[I] Total VCF records:         6616564
[I] Non-reference VCF records: 4691787
2020-02-13 22:22:54,382 ERROR    Command line view /tmp/tmpZpFEtyvcf.gz -R /data/reference_genome/panel_regions/all.bed.gz -o /tmp/truth.ppgUpq8m.vcf.gz -O z got return code 127.
STDOUT: 
STDERR: /bin/sh: 1: view: not found

2020-02-13 22:22:54,383 ERROR    Traceback (most recent call last):
2020-02-13 22:22:54,383 ERROR      File "/home/maxh/hap.py/bin/hap.py", line 529, in <module>
2020-02-13 22:22:54,384 ERROR        main()
2020-02-13 22:22:54,384 ERROR      File "/home/maxh/hap.py/bin/hap.py", line 309, in main
2020-02-13 22:22:54,384 ERROR        convert_gvcf_to_vcf=args.convert_gvcf_truth)
2020-02-13 22:22:54,385 ERROR      File "/home/maxh/hap.py/bin/pre.py", line 195, in preprocess
2020-02-13 22:22:54,385 ERROR        num_threads=threads)
2020-02-13 22:22:54,385 ERROR      File "/home/maxh/hap.py/lib/python27/Tools/bcftools.py", line 266, in preprocessVCF
2020-02-13 22:22:54,386 ERROR        raise ex
2020-02-13 22:22:54,386 ERROR    Exception: Command line view /tmp/tmpZpFEtyvcf.gz -R /data/reference_genome/panel_regions/all.bed.gz -o /tmp/truth.ppgUpq8m.vcf.gz -O z got return code 127.STDOUT: STDERR: /bin/sh: 1: view: not found
Hap.py v0.3.12
Error running BCFTOOLS; please check your file for compatibility issues issues using vcfcheck
```

I made my own docker container since the pkrusche one is 3 years old and I need hap.py to work with Octopus output. I had the smae issue with the provided dockerfiles though.

This is my dockerfile code:

```
FROM cannabinoid/base_conda_py2:0.1

RUN sudo apt-get update \
    && sudo apt-get install -y \
        build-essential \
        cmake \
        default-jdk \
        pkg-config \
        autoconf \
        bzip2 \
        libbz2-dev \
        libncurses5-dev \
        software-properties-common \
        zlib1g-dev

RUN conda update conda \
    && conda install \
        cython \
        scipy \
        numpy \
        pandas

RUN pip install pybedtools pysam bx-python

RUN sudo wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.7-bin.tar.gz \
    && sudo tar xzf apache-ant-1.9.7-bin.tar.gz \
    && sudo rm apache-ant-1.9.7-bin.tar.gz
ENV PATH $PATH:/home/$USERNAME/apache-ant-1.9.7/bin

RUN sudo git clone https://github.com/Illumina/hap.py.git

RUN cd hap.py \
    && sudo python install.py /home/$USERNAME/hap.py --with-rtgtools --no-tests
ENV PATH $PATH:/home/$USERNAME/hap.py/bin
```

**Comment by DBS-Max** [comment]
I tested with the pkrusche container with the same inputs and that container analyses fine.

The command I use is:

```
nohup docker run -v /media/maxh/slow_storage/human_data:/data pkrusche/hap.py \
    /opt/hap.py/bin/hap.py \
        -r /data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa \
        --engine=vcfeval \
        --engine-vcfeval-template /data/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla_sdf \
        --threads 5 \
        -R /data/reference_genome/panel_regions/all.bed.gz \
        -o /data/bwa_strelka2/eval/panel_regions_only_69_model_9_B82064 \
        /data/bwa_deepvariant/bcgc_30x/B82064_sorted_md.vcf.gz \
        /data/bwa_strelka2/panel_regions_only_69_model_9/results/variants/B82064.vcf.gz &
```

**Comment by dskola** [comment]
Hi @DBS-Max . This looks like a simple fix for now although all this command line manipulation code is in bad need of a refactoring. Can you try branch https://github.com/Illumina/hap.py/tree/issue_109 and see if it is fixed?

**Comment by DBS-Max** [comment]
That fixed it! Thanks for the quick reply :).
