### ISSUE TITLE
Faulty variant test fails

### ISSUE THREAD

**Issue by tirohia** [Illumina/hap.py#111]
As part of the install, the faulty variant test fails, with errors about not being able to convert non-finite values to NA or inf? Any idea what this could be referring to?

Attempting to install using the helper script as per [https://github.com/Illumina/hap.py#installation](https://github.com/Illumina/hap.py#installation) on a linux box, 
Linux version 4.19.0-041900-generic (kernel@tangerine) (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1))

```
Test for reading and detecting problematic records: Hap.py v0.3.12-2-g9d128a9 from /blue/project/benchmarking/bin/hap.py/bin
Hap.py v0.3.12-2-g9d128a9
[W] Unsupported REF allele with undefined length: A.
[W] Unsupported REF allele with undefined length: .A
[W] Alleles with uncertain length at chrQ:3
[W] Variants that have alleles with uncertain length: 2
[I] Total VCF records:         4
[I] Non-reference VCF records: 3
[W] Unsupported REF allele with undefined length: A.
[I] Total VCF records:         1
[I] Non-reference VCF records: 1
2020-02-20 14:54:57,957 WARNING  [W] Unsupported REF allele with undefined length: A.
2020-02-20 14:54:57,958 WARNING  Blocksplit returned no blocks. This can happen when an input contains no valid variants.
2020-02-20 14:54:58,055 WARNING  [W] Unsupported REF allele with undefined length at chrQ:1-1 REF allele: A.
2020-02-20 14:54:58,228 WARNING  [W] Unsupported REF allele with undefined length: A.
2020-02-20 14:54:58,228 WARNING  [W] Unsupported REF allele with undefined length: .A
2020-02-20 14:54:58,331 WARNING  [W] Unsupported REF allele with undefined length at chrQ:1-1 REF allele: A.
2020-02-20 14:54:58,331 WARNING  [W] Unsupported REF allele with undefined length at chrQ:2-2 REF allele: .A
2020-02-20 14:54:58,474 ERROR    Cannot convert non-finite values (NA or inf) to integer
2020-02-20 14:54:58,475 ERROR    Traceback (most recent call last):
2020-02-20 14:54:58,475 ERROR      File "/blue/project/benchmarking/bin/hap.py/bin/hap.py", line 529, in <module>
2020-02-20 14:54:58,475 ERROR        main()
2020-02-20 14:54:58,475 ERROR      File "/blue/project/benchmarking/bin/hap.py/bin/hap.py", line 514, in main
2020-02-20 14:54:58,475 ERROR        qfy.quantify(args)
2020-02-20 14:54:58,475 ERROR      File "/blue/project/benchmarking/bin/hap.py/bin/qfy.py", line 154, in quantify
2020-02-20 14:54:58,475 ERROR        total_region_size=total_region_size)
2020-02-20 14:54:58,475 ERROR      File "/blue/project/benchmarking/bin/hap.py/lib/python27/Haplo/happyroc.py", line 168, in roc
2020-02-20 14:54:58,476 ERROR        result["all"][c] = result["all"][c].astype(RESULT_ALLDTYPES[i], raise_on_error=False)
2020-02-20 14:54:58,476 ERROR      File "/home/bcurran/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 5691, in astype
2020-02-20 14:54:58,478 ERROR        **kwargs)
2020-02-20 14:54:58,478 ERROR      File "/home/bcurran/.local/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 531, in astype
2020-02-20 14:54:58,478 ERROR        return self.apply('astype', dtype=dtype, **kwargs)
2020-02-20 14:54:58,478 ERROR      File "/home/bcurran/.local/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 395, in apply
2020-02-20 14:54:58,478 ERROR        applied = getattr(b, f)(**kwargs)
2020-02-20 14:54:58,478 ERROR      File "/home/bcurran/.local/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 534, in astype
2020-02-20 14:54:58,479 ERROR        **kwargs)
2020-02-20 14:54:58,479 ERROR      File "/home/bcurran/.local/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 633, in _astype
2020-02-20 14:54:58,479 ERROR        values = astype_nansafe(values.ravel(), dtype, copy=True)
2020-02-20 14:54:58,479 ERROR      File "/home/bcurran/.local/lib/python2.7/site-packages/pandas/core/dtypes/cast.py", line 676, in astype_nansafe
2020-02-20 14:54:58,479 ERROR        raise ValueError('Cannot convert non-finite values (NA or inf) to '
2020-02-20 14:54:58,479 ERROR    ValueError: Cannot convert non-finite values (NA or inf) to integer
hap.py failed!
Faulty variant test FAILED!

```

**Comment by Lenbok** [comment]
This a duplicate of #95
(I don't know why the test is failing though, someone at Illumina like @dskola who is familiar with the hap.py code can help)

**Comment by tirohia** [comment]
It does look similar yes. I'll close this one and follow #95 

Cheers
Ben.
