### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by a00101** [Illumina/hap.py#121]
`# hap.py NA12878.vcf.gz 01.Raw_variants.vcf.gz -f ConfidentRegions.bed.gz -o test -r hg38.fa
`
```
[I] Total VCF records:         4167900
[I] Non-reference VCF records: 4167900
[W] overlapping records at chr1:37070742 for sample 0
[W] Variants that overlap on the reference allele: 58
[I] Total VCF records:         1172477
[I] Non-reference VCF records: 1171661
2020-07-29 11:40:37,843 ERROR    [stderr] regex_error
2020-07-29 11:40:37,932 ERROR    Command 'quantify /tmp/hap.py.result.KDYrhc.vcf.gz -o test.roc.tsv -r hg38.fa --threads 80 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test.vcf.gz -R 'CONF_VARS:/tmp/tmpDLVB93.bed' -R 'CONF:ConfidentRegions.bed.gz' --roc-regions '*'' returned non-zero exit status 1
2020-07-29 11:40:37,933 ERROR    Traceback (most recent call last):
2020-07-29 11:40:37,933 ERROR      File "/root/anaconda3/envs/happy/bin/hap.py", line 511, in <module>
2020-07-29 11:40:37,934 ERROR        main()
2020-07-29 11:40:37,934 ERROR      File "/root/anaconda3/envs/happy/bin/hap.py", line 496, in main
2020-07-29 11:40:37,934 ERROR        qfy.quantify(args)
2020-07-29 11:40:37,934 ERROR      File "/root/anaconda3/envs/happy/bin/qfy.py", line 129, in quantify
2020-07-29 11:40:37,935 ERROR        strat_fixchr=args.strat_fixchr)
2020-07-29 11:40:37,935 ERROR      File "/root/anaconda3/envs/happy/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2020-07-29 11:40:37,935 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2020-07-29 11:40:37,935 ERROR      File "/root/anaconda3/envs/happy/lib/python2.7/subprocess.py", line 190, in check_call
2020-07-29 11:40:37,936 ERROR        raise CalledProcessError(retcode, cmd)
2020-07-29 11:40:37,937 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.KDYrhc.vcf.gz -o test.roc.tsv -r hg38.fa --threads 80 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test.vcf.gz -R 'CONF_VARS:/tmp/tmpDLVB93.bed' -R 'CONF:ConfidentRegions.bed.gz' --roc-regions '*'' returned non-zero exit status 1

```

**Comment by christinafliege** [comment]
Incidentally, I am getting an error at the same record in the VCF for pre.py

```
chr1    37070742        rs66730050      ACG     A,ATGCG 857.73  PASS    AC=1,1;AF=0.5,0.5;AN=2;DB;DP=22;ExcessHet=3.0103;FS=0.000;MLEAC=1,1;MLEAF=0.5,0.5;MQ=60.00;QD=45.14;SOR=0.793;VQSLOD=3.8585;culprit=FS  GT:AD:DP:GQ:PL  1/2:0,9,10:19:99:895,417,379,387,0,348

**Comment by joys8998** [comment]
@a00101 and @christinafliege Did you solve the issue? How did you do? Because I get the same error but I have noclue about how to fix it.
Thanks!

**Comment by xmy1990** [comment]
hi @https://github.com/b-math
Which version of python2 did you use?
I have successed to install hap.py=0.3.14, bur failed to run hap.py with the same error:
returned non-zero exit status 1

Thanks!

**Comment by ESDeutekom** [comment]
Hello @pkrusche, wondering if this is being looked into? I am also not able to use the tool
