### ISSUE TITLE
pre.py for normalization errors

### ISSUE THREAD

**Issue by christinafliege** [Illumina/hap.py#122]
Good Afternoon,
I am attempting to use pre.py to normalize VCFs.  However, I am getting the following errors with this command.  I have tried this on a few different VCFs from different sources

```
pre.py  zip30X_background.golden.vcf Normedzip30X_background.godilen.vcf  --set-gt hom --threads 10 -L -D -r /projects/bioinformatics/DataPacks/human/gatk_bundle_Oct_2017/gatk_bundle_hg38/Homo_sapiens_assembly38.fasta


Traceback (most recent call last):
  File "/usr/local/apps/bioapps/hap.py/hap.py-0.3.12/hap.py-build/bin/pre.py", line 408, in <module>
    main()
  File "/usr/local/apps/bioapps/hap.py/hap.py-0.3.12/hap.py-build/bin/pre.py", line 404, in main
    preprocessWrapper(args)
  File "/usr/local/apps/bioapps/hap.py/hap.py-0.3.12/hap.py-build/bin/pre.py", line 245, in preprocessWrapper
    convert_gvcf_to_vcf=args.convert_gvcf)
AttributeError: 'Namespace' object has no attribute 'convert_gvcf'

**Comment by egenomics** [comment]
Same problem here

**Comment by christinafliege** [comment]
@egenomics 
https://github.com/Illumina/hap.py/issues/106
this issue shows a workaround that worked for this error.

**Comment by hguturu** [comment]
Should be closed since #113 was merged.
