### ISSUE TITLE
blocksplit failing, is there a workaround?

### ISSUE THREAD

**Issue by umylny-dls** [Illumina/hap.py#128]
Blocksplit consistently failing with:

W] overlapping records at chr1:3181487 for sample 0
[W] Variants that overlap on the reference allele: 664
[I] Total VCF records:         5088629
[I] Non-reference VCF records: 5088629
[W] overlapping records at chr1:3181487 for sample 0
[W] Variants that overlap on the reference allele: 646
[I] Total VCF records:         5089804
[I] Non-reference VCF records: 5089804
2020-09-24 08:43:58,033 WARNING  stoll
2020-09-24 08:43:58,034 ERROR    Exception when running <function blocksplitWrapper at 0x2aab4b3b58c0>:
2020-09-24 08:43:58,034 ERROR    ------------------------------------------------------------
2020-09-24 08:43:58,034 ERROR    Traceback (most recent call last):
2020-09-24 08:43:58,034 ERROR      File "/gpfs/gpfs1/dls/home/boris.umylny/tools/hap.py-install/lib/python27/Tools/parallel.py", line 72, in parMapper
2020-09-24 08:43:58,045 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2020-09-24 08:43:58,046 ERROR      File "/gpfs/gpfs1/dls/home/boris.umylny/tools/hap.py-install/lib/python27/Haplo/partialcredit.py", line 121, in blocksplitWrapper
2020-09-24 08:43:59,262 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2020-09-24 08:43:59,262 ERROR      File "/gpfs/gpfs2/software/python-2.7.15/lib/python2.7/subprocess.py", line 190, in check_call
2020-09-24 08:43:59,318 ERROR        raise CalledProcessError(retcode, cmd)
2020-09-24 08:43:59,318 ERROR    CalledProcessError: Command 'blocksplit /tmp/tmpizcs_Y.vcf.gz -l 'HLA-DRB1*09:21' -o /tmp/result.HLA-DRB1*09:213nNjWI.chunks.bed --window 10000 --nblocks 40 -f 0' returned non-zero exit status 1
2020-09-24 08:43:59,318 ERROR    ------------------------------------------------------------
2020-09-24 08:44:05,143 ERROR    One of the blocksplit processes failed.
2020-09-24 08:44:05,143 ERROR    Traceback (most recent call last):
2020-09-24 08:44:05,143 ERROR      File "/gpfs/gpfs1/dls/home/boris.umylny/tools/hap.py-install/bin/hap.py", line 529, in <module>
2020-09-24 08:44:05,147 ERROR        main()
2020-09-24 08:44:05,147 ERROR      File "/gpfs/gpfs1/dls/home/boris.umylny/tools/hap.py-install/bin/hap.py", line 383, in main
2020-09-24 08:44:05,147 ERROR        convert_gvcf_to_vcf=args.convert_gvcf_query)
2020-09-24 08:44:05,147 ERROR      File "/gpfs/gpfs1/dls/home/boris.umylny/tools/hap.py-install/bin/pre.py", line 206, in preprocess
2020-09-24 08:44:05,167 ERROR        haploid_x=gender == "male")
2020-09-24 08:44:05,168 ERROR      File "/gpfs/gpfs1/dls/home/boris.umylny/tools/hap.py-install/lib/python27/Haplo/partialcredit.py", line 192, in partialCredit
2020-09-24 08:44:05,168 ERROR        raise Exception("One of the blocksplit processes failed.")
2020-09-24 08:44:05,168 ERROR    Exception: One of the blocksplit processes failed.

**Comment by joshfactorial** [comment]
I'm having the same problem
