### ISSUE TITLE
install.py failed when Multimerge test

### ISSUE THREAD

**Issue by wangyugui** [Illumina/hap.py#13]
install.py failed when Multimerge test

source version:current version(commit d51d111e494b561b37c66299daf5a6c65a8d2ca9)

```
#./install.py --python system  /usr/hpc-bio/hap.py
...
...
...
Running Multimerge test (1)
Adding file '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/merge1.vcf.gz' / sample 'NA12877'
Adding file '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/merge2.vcf.gz' / sample 'NA12878'
Writing '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/merge1.vcf.gz:NA12877' as sample 'NA12877'
Writing '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/merge2.vcf.gz:NA12878' as sample 'NA12878'
Multimerge test SUCCEEDED.
Running Multimerge data import test
Adding file '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/import_errors.vcf.gz' / sample 'NA12877'
Writing '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/import_errors.vcf.gz:NA12877' as sample 'NA12877'
[W] Found a variant with more 3 > 2 (max) alt alleles. These become no-calls.
Multimerge test SUCCEEDED.
Running Multimerge test (2)
Output is in /tmp/multimerge.nKc2BbJ3L8.vcf
Adding file '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../../example/multimerge/hap_alleles_1.vcf.gz' / sample ''
Adding file '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../../example/multimerge/hap_alleles_2.vcf.gz' / sample ''
Writing '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../../example/multimerge/hap_alleles_1.vcf.gz:' as sample 'hap_alleles_1.vcf'
Writing '/nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../../example/multimerge/hap_alleles_2.vcf.gz:' as sample 'hap_alleles_2.vcf'
[W::vcf_parse_format] FORMAT 'GT' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'GT' is not defined in the header, assuming Type=String
Contig chr1 is not known
35a35,40
> chr1  19472002        .       GACACACACACACACACACAC   G       0       .       .       GT      0/1     0/1
> chr1  19472022        .       C       CAC     0       .       .       GT      ./.     0/1
> chr1  19472022        .       C       CAC     0       .       .       GT      0/1     ./.
> chr1  31755330        .       GTATCTATC       G       0       .       .       GT      0/1     0/1
> chr1  31755334        .       CTATC   C       0       .       .       GT      ./.     0/1
> chr1  31755334        .       CTATC   C       0       .       .       GT      0/1     ./.
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##reference=hg19
##contig=<ID=chr1,length=249250621>
##contig=<ID=chr2,length=243199373>
##contig=<ID=chr3,length=198022430>
##contig=<ID=chr4,length=191154276>
##contig=<ID=chr5,length=180915260>
##contig=<ID=chr6,length=171115067>
##contig=<ID=chr7,length=159138663>
##contig=<ID=chr8,length=146364022>
##contig=<ID=chr9,length=141213431>
##contig=<ID=chr10,length=135534747>
##contig=<ID=chr11,length=135006516>
##contig=<ID=chr12,length=133851895>
##contig=<ID=chr13,length=115169878>
##contig=<ID=chr14,length=107349540>
##contig=<ID=chr15,length=102531392>
##contig=<ID=chr16,length=90354753>
##contig=<ID=chr17,length=81195210>
##contig=<ID=chr18,length=78077248>
##contig=<ID=chr19,length=59128983>
##contig=<ID=chr20,length=63025520>
##contig=<ID=chr21,length=48129895>
##contig=<ID=chr22,length=51304566>
##contig=<ID=chrX,length=155270560>
##INFO=<ID=END,Number=.,Type=Integer,Description="SV end position">
##INFO=<ID=IMPORT_FAIL,Number=.,Type=Flag,Description="Flag to identify variants that could not be imported.">
##FORMAT=<ID=AGT,Number=1,Type=String,Description="Genotypes at ambiguous locations">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=AD,Number=A,Type=Integer,Description="Allele Depths">
##FORMAT=<ID=ADO,Number=.,Type=Integer,Description="Summed depth of non-called alleles.">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  hap_alleles_1.vcf       hap_alleles_2.vcf
Multimerge test (2) FAILED. diff -I^# /tmp/multimerge.nKc2BbJ3L8.vcf /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../../example/multimerge/hap_alleles_leftshifted.vcf
Multimerge tests FAILED!
Traceback (most recent call last):
  File "./install.py", line 334, in <module>
    main()
  File "./install.py", line 330, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "./install.py", line 199, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /usr/hpc-bio/hap.py && /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1

```

**Comment by pkrusche** [comment]
I cannot reproduce this here, could you please provide details on 

* linux version used
* compiler versions (gcc / g++)

Also, does the system Python that is being used have all required dependencies installed (Cython, numpy, pandas, -- everything that's inhttps://github.com/Illumina/hap.py/blob/master/happy.requirements.txt ) ?

Thanks!

**Comment by wangyugui** [comment]
Linux version:CentOS 7.3(3.10.0-514.10.2.el7.x86_64)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

After install some requirements, The error message changed.
```
yum install -y python2-pip Cython numpy python-pandas python-nose scipy
pip install pysam
pip install pybedtools
pip install https://bitbucket.org/pkrusche/bx-python/get/tip.tar.bz2
#./install.py --python system  /usr/hpc-bio/hap.py
...
...
...
2017-03-14 06:20:35,360 ERROR    Command 'quantify /tmp/hap.py.result.LVQ74m.vcf.gz -o /tmp/happy.zcxbdz1zCw.roc.tsv -r /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/pathtraversal/test.fa --threads 48 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v /tmp/happy.zcxbdz1zCw.vcf.gz --roc-regions '*'' returned non-zero exit status 1
2017-03-14 06:20:35,361 ERROR    Traceback (most recent call last):
2017-03-14 06:20:35,361 ERROR      File "/usr/hpc-bio/hap.py/bin/hap.py", line 460, in <module>
2017-03-14 06:20:35,361 ERROR        main()
2017-03-14 06:20:35,362 ERROR      File "/usr/hpc-bio/hap.py/bin/hap.py", line 445, in main
2017-03-14 06:20:35,362 ERROR        qfy.quantify(args)
2017-03-14 06:20:35,362 ERROR      File "/usr/hpc-bio/hap.py/bin/qfy.py", line 129, in quantify
2017-03-14 06:20:35,362 ERROR        strat_fixchr=args.strat_fixchr)
2017-03-14 06:20:35,362 ERROR      File "/usr/hpc-bio/hap.py/lib/python27/Haplo/quantify.py", line 178, in run_quantify
2017-03-14 06:20:35,363 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2017-03-14 06:20:35,363 ERROR      File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
2017-03-14 06:20:35,364 ERROR        raise CalledProcessError(retcode, cmd)
2017-03-14 06:20:35,364 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.LVQ74m.vcf.gz -o /tmp/happy.zcxbdz1zCw.roc.tsv -r /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/pathtraversal/test.fa --threads 48 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v /tmp/happy.zcxbdz1zCw.vcf.gz --roc-regions '*'' returned non-zero exit status 1
hap.py failed!
Path traversal test FAILED!
Traceback (most recent call last):
  File "./install.py", line 334, in <module>
    main()
  File "./install.py", line 330, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "./install.py", line 199, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /usr/hpc-bio/hap.py && /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1

#
# quantify /tmp/hap.py.result.LVQ74m.vcf.gz -o /tmp/happy.zcxbdz1zCw.roc.tsv -r /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/../data/pathtraversal/test.fa --threads 48 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v /tmp/happy.zcxbdz1zCw.vcf.gz --roc-regions '*'
regex_error
# which quantify
/usr/hpc-bio/hap.py/bin/quantify
```

**Comment by pkrusche** [comment]
The regex error is related to using gcc 4.8. Hap.py requires at least gcc 4.9 (the next release will document this properly).

**Comment by wangyugui** [comment]
gcc 4.8 is the default gcc in RHEL7/CentOS 7.

Can we add the support of GCC 4.8 to hay.py?

**Comment by pkrusche** [comment]
Centos has a newer gcc in SCL / Devtoolset3 I think: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/ /  https://superuser.com/a/1027865

I am happy to review a PR to add backwards-compatibility to 4.8, but long term this is not on my list of priorities and I won't have the time to implement this myself. The code that would need changing is here: https://github.com/Illumina/hap.py/blob/master/src/c%2B%2B/lib/quantify/QuantifyRegions.cpp#L105 / https://github.com/Illumina/hap.py/blob/master/src/c%2B%2B/lib/quantify/QuantifyRegions.cpp#L242 -- this uses a C++ STL Regex, it could be changed over to use the same functionality from Boost.

**Comment by pkrusche** [comment]
Another option (if SCL / GCC isn't an option in the target environment) is to build a Centos binary distribution using Docker, this can be achieved by changing this Dockerfile:

https://github.com/Illumina/hap.py/blob/master/Dockerfile.centos6 

Note this file is currently broken (it installs devtoolset-2, which is too old). Here is a fixed version that should work:

```
FROM centos:6.7

ENV HOME /root
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN  yum install -y wget curl tar gzip bzip2 which perl

RUN  mkdir -p /opt/illumina/haplocompare && \
     cd /opt/illumina/haplocompare && \
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh && \
     bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/miniconda2

ENV PATH /opt/miniconda2/bin:${PATH}

RUN  yum install -y centos-release-scl && \
     yum install -y devtoolset-3-gcc devtoolset-3-binutils && \
     yum install -y devtoolset-3-gcc-c++ devtoolset-3-gcc-gfortran && \
     yum install -y cmake bzip2-devel ncurses-devel zlib-devel

RUN  conda config --add channels bioconda && \
     conda install -y cython numpy scipy biopython matplotlib pandas pysam bx-python pyvcf cyvcf2 nose

RUN yum upgrade -y && yum update -y && yum clean all

COPY . /opt/illumina/haplocompare/hap.py-source
WORKDIR /opt/illumina/haplocompare/hap.py-source

# patch samtools for centos 6
RUN  cd external && \
     tar xvzf samtools.tar.gz && \
     cd samtools && \
     cat Makefile | sed 's/-ldl/-ldl -ltinfo/' > Makefile.bak && \
     mv -f Makefile.bak Makefile && \
     cd .. && \
     rm -f samtools.tar.gz && \
     tar czvf samtools.tar.gz samtools


ENV JDK_VERSION 8u11
ENV JDK_BUILD_VERSION b12
RUN curl -LO "http://download.oracle.com/otn-pub/java/jdk/$JDK_VERSION-$JDK_BUILD_VERSION/jdk-$JDK_VERSION-linux-x64.rpm" -H 'Cookie: oraclelicense=accept-securebackup-cookie' && rpm -i jdk-$JDK_VERSION-linux-x64.rpm; rm -f jdk-$JDK_VERSION-linux-x64.rpm; yum clean all
ENV JAVA_HOME /usr/java/default

RUN  mkdir -p /opt/illumina/haplocompare/data && \
     cd /opt/illumina/haplocompare/data && \
     bash /opt/illumina/haplocompare/hap.py-source/src/sh/make_hg19.sh

ENV HG19 /opt/illumina/haplocompare/data/hg19.fa

RUN scl enable devtoolset-3 'python install.py /opt/illumina/haplocompare/hap.py --with-rtgtools'
```

**Comment by wangyugui** [comment]
Thanks for your info. I will try Devtoolset.

**Comment by wangyugui** [comment]
I have installed gcc 5.3 and there still some other errors.

error:
```
Traceback (most recent call last):
  File "./install.py", line 334, in <module>
    main()
  File "./install.py", line 330, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "./install.py", line 199, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /usr/hpc-bio/hap.py && /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1
```

detail:
```
#cd /usr/hpc-bio/hap.py && /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/run_tests.sh

2017-03-15 08:56:31,884 ERROR    coercing to Unicode: need string or buffer, NoneType found
2017-03-15 08:56:31,884 ERROR    Traceback (most recent call last):
2017-03-15 08:56:31,884 ERROR      File "/usr/hpc-bio/hap.py/bin/hap.py", line 460, in <module>
2017-03-15 08:56:31,884 ERROR        main()
2017-03-15 08:56:31,884 ERROR      File "/usr/hpc-bio/hap.py/bin/hap.py", line 199, in main
2017-03-15 08:56:31,884 ERROR        if not os.path.exists(args.ref):
2017-03-15 08:56:31,884 ERROR      File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
2017-03-15 08:56:31,885 ERROR        os.stat(path)
2017-03-15 08:56:31,885 ERROR    TypeError: coercing to Unicode: need string or buffer, NoneType found
hap.py failed!
Variant decomposition test FAILED!


```

**Comment by wangyugui** [comment]
This error happen on Fedora 25 too.
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

**Comment by pkrusche** [comment]
This error is caused by hap.py not finding a reference in the default location. It should be fixable by obtaining a hg19 reference and pointing hap.py to it using an environment variable:

```
export HGREF=<path-to-hg19.fa>
cd /usr/hpc-bio/hap.py && /nfs/git/dna/benchmarking-tools/tools/hap.py/src/sh/run_tests.sh
```

**Comment by pkrusche** [comment]
Hap.py also has a script to create such a reference fasta file (any hg19 reference will do):

https://github.com/Illumina/hap.py/blob/master/src/sh/make_hg19.sh

I will add an option to the installer for the next release to fix the default path such that this error can be avoided.

**Comment by wangyugui** [comment]
Thanks for nice support. 
install.py worked when HGREF is set.

please close this issue.

**Comment by pkrusche** [comment]
Happy you managed to make it work!
