### ISSUE TITLE
Installation issues in Centos7

### ISSUE THREAD

**Issue by KrithikaSubramanian** [Illumina/hap.py#132]
Hi,

I am Krithika S. Currently I am trying to use Hap.py for my analysis. While installing I am getting the following errors.

**[root@localhost bin]# python hap.py --version**
  File "hap.py", line 187
    print "Hap.py %s" % Tools.version        
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Hap.py %s" % Tools.version)?

Could you please help to fix this issues.

Thanks in advance
Krithika S

**Comment by blmoore** [comment]
Your system python may be python 3 whereas hap.py needs python 2:
```
python2 hap.py --version
```

**Comment by KrithikaSubramanian** [comment]
Thanks for your reply. 

Could you please help me the following error.

**command used**
_python2 hap.py-0.3.12/bin/hap.py high_conf.vcf query.vcf -f /highconf_chr22.bed -r ref.fa -o chr22_

**Log**
Hap.py 
[I] Total VCF records:         42190
[I] Non-reference VCF records: 42190
[I] Total VCF records:         6907083
[I] Non-reference VCF records: 0
2020-11-20 12:37:21,211 WARNING  Blocksplit returned no blocks. This can happen when an input contains no valid variants.
2020-11-20 12:37:22,621 ERROR    Preprocess command preprocess /tmp/tmpqAYcLy.vcf.gz:* -o /tmp/input.qmM39b.prep.vcf.gz -V 1 -L 1 -r ref.fa failed. Outputs are here /tmp/stdoutqDPH_r.log / /tmp/stderrdAwzTO.log
2020-11-20 12:37:22,622 ERROR    [W] too many AD fields at chr22:10514640 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,622 ERROR    [W] too many AD fields at chr22:10514993 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10515353 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516101 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516149 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516150 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516151 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516226 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516227 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516228 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,623 ERROR    [W] too many AD fields at chr22:10516229 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10516230 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10516231 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10516232 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10516233 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10516234 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10519087 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10519427 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10519562 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,624 ERROR    [W] too many AD fields at chr22:10519564 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10519601 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10519628 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10519972 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10521825 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10522689 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10522818 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10524842 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10524879 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10524953 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,625 ERROR    [W] too many AD fields at chr22:10526057 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10526435 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10526437 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10526444 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10526738 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10526798 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10527073 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10527250 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10527528 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,626 ERROR    [W] too many AD fields at chr22:10530520 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530521 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530522 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530523 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530524 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530525 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530526 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530527 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10530528 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10531299 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,627 ERROR    [W] too many AD fields at chr22:10531300 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531301 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531302 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531303 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531304 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531305 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531306 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531307 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531407 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,628 ERROR    [W] too many AD fields at chr22:10531442 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10531933 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10532286 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534230 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534335 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534383 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534399 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534403 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534559 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534560 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,629 ERROR    [W] too many AD fields at chr22:10534561 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534562 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534563 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534564 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534648 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534659 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534665 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10534787 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10535036 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,630 ERROR    [W] too many AD fields at chr22:10537094 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10552172 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10554095 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10554544 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10554688 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10557622 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10557810 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10557961 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10557985 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10558150 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,631 ERROR    [W] too many AD fields at chr22:10558197 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10558766 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10558954 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10559719 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10559729 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10560579 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10560890 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10560893 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10560915 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10560957 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,632 ERROR    [W] too many AD fields at chr22:10561170 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561258 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561281 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561354 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561457 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561587 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561790 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    [W] too many AD fields at chr22:10561791 max_ad = 2 retrieved: 3
2020-11-20 12:37:22,633 ERROR    Exception when running <function preprocessWrapper at 0x7fc8d2ed1500>:
2020-11-20 12:37:22,633 ERROR    ------------------------------------------------------------
2020-11-20 12:37:22,634 ERROR    Traceback (most recent call last):
2020-11-20 12:37:22,634 ERROR      File "/home/dell_backup_26_12_19/Krithika_hap/hap.py-0.3.12/lib/python27/Tools/parallel.py", line 71, in parMapper
2020-11-20 12:37:22,634 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2020-11-20 12:37:22,634 ERROR      File "/home/dell_backup_26_12_19/Krithika_hap/hap.py-0.3.12/lib/python27/Haplo/partialcredit.py", line 66, in preprocessWrapper
2020-11-20 12:37:22,635 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2020-11-20 12:37:22,635 ERROR      File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
2020-11-20 12:37:22,636 ERROR        raise CalledProcessError(retcode, cmd)
2020-11-20 12:37:22,636 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpqAYcLy.vcf.gz:* -o /tmp/input.qmM39b.prep.vcf.gz -V 1 -L 1 -r /home/dell_backup_26_12_19/Krithika_hap/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa' returned non-zero exit status -11
2020-11-20 12:37:22,636 ERROR    ------------------------------------------------------------
2020-11-20 12:37:22,667 ERROR    One of the preprocess jobs failed
2020-11-20 12:37:22,668 ERROR    Traceback (most recent call last):
2020-11-20 12:37:22,668 ERROR      File "/home/dell_backup_26_12_19/Krithika_hap/hap.py-0.3.12/bin/hap.py", line 529, in <module>
2020-11-20 12:37:22,668 ERROR        main()
2020-11-20 12:37:22,669 ERROR      File "/home/dell_backup_26_12_19/Krithika_hap/hap.py-0.3.12/bin/hap.py", line 383, in main
2020-11-20 12:37:22,669 ERROR        convert_gvcf_to_vcf=args.convert_gvcf_query)
2020-11-20 12:37:22,669 ERROR      File "/home/dell_backup_26_12_19/Krithika_hap/hap.py-0.3.12/bin/pre.py", line 206, in preprocess
2020-11-20 12:37:22,669 ERROR        haploid_x=gender == "male")
2020-11-20 12:37:22,669 ERROR      File "/home/dell_backup_26_12_19/Krithika_hap/hap.py-0.3.12/lib/python27/Haplo/partialcredit.py", line 213, in partialCredit
2020-11-20 12:37:22,670 ERROR        raise Exception("One of the preprocess jobs failed")
2020-11-20 12:37:22,670 ERROR    Exception: One of the preprocess jobs failed

Regards
Krithika S
