### ISSUE TITLE
One of the preprocess jobs failed. Cannot query reference sequence

### ISSUE THREAD

**Issue by jcs3632** [Illumina/hap.py#136]
Last week, I was seeing the same issue described here https://github.com/Illumina/hap.py/pull/135. After the fix, I reinstalled hap.py using CMake and no longer see the ```args.convert_gvcf_truth``` error when I run the example hap.py command. However, I am seeing another issue when I run the example command.

```
python bin/hap.py /storage/jak/home/sam/hap.py/example/happy/PG_NA12878_chr21.vcf.gz /storage/jak/home/sam/hap.py/example/happy/NA12878_chr21.vcf.gz -f /storage/jak/home/sam/hap.py/example/happy/PG_Conf_chr21.bed.gz -o test
```

Here's the error.
```
Hap.py v0.3.14
[W] overlapping records at chr21:10993857 for sample 0
[W] Symbolic / SV ALT alleles at chr21:15847469
[W] Variants that overlap on the reference allele: 144
[W] Variants that have symbolic ALT alleles: 14
[I] Total VCF records:         65402
[I] Non-reference VCF records: 65402
[W] overlapping records at chr21:24024261 for sample 0
[W] Variants that overlap on the reference allele: 5
[I] Total VCF records:         101524
[I] Non-reference VCF records: 101524
2021-03-23 12:40:26,111 ERROR    Preprocess command preprocess /storage/jak/tmp/tmpDDlCrQ.vcf.gz:* -l chr21:46758486-2147483647 -o /storage/jak/tmp/input.chr21:46758486-21474836473lyfwX.prep.vcf.gz -V 1 -L 1 -r /storage/jak/home/sam/hap.py/example/happy/hg38.chr21.fa failed. Outputs are here /storage/jak/tmp/stdoutvatKue.log / /storage/jak/tmp/stderrWDdVBU.log
2021-03-23 12:40:26,113 ERROR    Cannot query reference sequence at :46760354-46760354
2021-03-23 12:40:26,113 ERROR    Exception when running <function preprocessWrapper at 0x7f0f1b4bfe50>:
2021-03-23 12:40:26,113 ERROR    ------------------------------------------------------------
2021-03-23 12:40:26,113 ERROR    Traceback (most recent call last):
2021-03-23 12:40:26,113 ERROR      File "/storage/jak/home/sam/hap.py-build/lib/python27/Tools/parallel.py", line 71, in parMapper
2021-03-23 12:40:26,135 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2021-03-23 12:40:26,135 ERROR      File "/storage/jak/home/sam/hap.py-build/lib/python27/Haplo/partialcredit.py", line 66, in preprocessWrapper
2021-03-23 12:40:26,238 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2021-03-23 12:40:26,238 ERROR      File "/storage/jak/home/sam/miniconda/envs/py2/lib/python2.7/subprocess.py", line 190, in check_call
2021-03-23 12:40:26,242 ERROR        raise CalledProcessError(retcode, cmd)
2021-03-23 12:40:26,242 ERROR    CalledProcessError: Command 'preprocess /storage/jak/tmp/tmpDDlCrQ.vcf.gz:* -l chr21:46758486-2147483647 -o /storage/jak/tmp/input.chr21:46758486-21474836473lyfwX.prep.vcf.gz -V 1 -L 1 -r /storage/jak/home/sam/hap.py/example/happy/hg38.chr21.fa' returned non-zero exit status 1
2021-03-23 12:40:26,242 ERROR    ------------------------------------------------------------
2021-03-23 12:40:28,019 ERROR    Preprocess command preprocess /storage/jak/tmp/tmpDDlCrQ.vcf.gz:* -l chr21:44642557-46758485 -o /storage/jak/tmp/input.chr21:44642557-46758485KqOMOG.prep.vcf.gz -V 1 -L 1 -r /storage/jak/home/sam/hap.py/example/happy/hg38.chr21.fa failed. Outputs are here /storage/jak/tmp/stdout2VFOTz.log / /storage/jak/tmp/stderrQm2vFb.log
2021-03-23 12:40:28,020 ERROR    Cannot query reference sequence at :46710276-46710276
2021-03-23 12:40:28,020 ERROR    Exception when running <function preprocessWrapper at 0x7f0f1b4bfe50>:
2021-03-23 12:40:28,020 ERROR    ------------------------------------------------------------
2021-03-23 12:40:28,020 ERROR    Traceback (most recent call last):
2021-03-23 12:40:28,020 ERROR      File "/storage/jak/home/sam/hap.py-build/lib/python27/Tools/parallel.py", line 71, in parMapper
2021-03-23 12:40:28,020 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2021-03-23 12:40:28,020 ERROR      File "/storage/jak/home/sam/hap.py-build/lib/python27/Haplo/partialcredit.py", line 66, in preprocessWrapper
2021-03-23 12:40:28,021 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2021-03-23 12:40:28,021 ERROR      File "/storage/jak/home/sam/miniconda/envs/py2/lib/python2.7/subprocess.py", line 190, in check_call
2021-03-23 12:40:28,021 ERROR        raise CalledProcessError(retcode, cmd)
2021-03-23 12:40:28,021 ERROR    CalledProcessError: Command 'preprocess /storage/jak/tmp/tmpDDlCrQ.vcf.gz:* -l chr21:44642557-46758485 -o /storage/jak/tmp/input.chr21:44642557-46758485KqOMOG.prep.vcf.gz -V 1 -L 1 -r /storage/jak/home/sam/hap.py/example/happy/hg38.chr21.fa' returned non-zero exit status 1
2021-03-23 12:40:28,022 ERROR    ------------------------------------------------------------
2021-03-23 12:40:33,412 ERROR    One of the preprocess jobs failed
2021-03-23 12:40:33,412 ERROR    Traceback (most recent call last):
2021-03-23 12:40:33,412 ERROR      File "hap.py", line 540, in <module>
2021-03-23 12:40:33,413 ERROR        main()
2021-03-23 12:40:33,413 ERROR      File "hap.py", line 394, in main
2021-03-23 12:40:33,413 ERROR        convert_gvcf_to_vcf=convert_gvcf_query)
2021-03-23 12:40:33,413 ERROR      File "/storage/jak/home/sam/hap.py-build/bin/pre.py", line 206, in preprocess
2021-03-23 12:40:33,414 ERROR        haploid_x=gender == "male")
2021-03-23 12:40:33,414 ERROR      File "/storage/jak/home/sam/hap.py-build/lib/python27/Haplo/partialcredit.py", line 213, in partialCredit
2021-03-23 12:40:33,415 ERROR        raise Exception("One of the preprocess jobs failed")
2021-03-23 12:40:33,415 ERROR    Exception: One of the preprocess jobs failed
```
Is there something else I'm missing? 
I also exported the path for HGREF and was able to run som.py without any errors. 
```
export HGREF=/storage/jak/home/sam/hap.py/example/happy/hg38.chr21.fa
```

**Comment by jcs3632** [comment]
Looks like the issue is with the bedfile or the reference. I ran the code below without errors.
```python ~/hap.py-build/bin/hap.py ~/hap.py/example/happy/PG_NA12878_chr21.vcf.gz ~/hap.py/example/happy/NA12878_chr21.vcf.gz -o test -r ~/hap.py/example/chr21.fa```
