### ISSUE TITLE
Don't find the reference

### ISSUE THREAD

**Issue by kangxiongbin** [Illumina/hap.py#161]
**CODE:**

hap.py 40X_deepvariant_illumina_tumor_only.vcf 40X_PEPPER_MARGIN_tumor_only.vcf -r /public/groups/vg/xkang12/data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta -o hap_result/

**ISSUE:**

WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
Hap.py 
2022-07-26 17:27:00,351 ERROR    The output path should specify a file name prefix. Please specify a valid output path and prefix using -o. For example, -o /tmp/test will create files named /tmp/test* .
2022-07-26 17:27:00,352 ERROR    Traceback (most recent call last):
2022-07-26 17:27:00,352 ERROR      File "/public/home/xkang12/software/miniconda3/envs/py2/bin/hap.py", line 540, in <module>
2022-07-26 17:27:00,352 ERROR        main()
2022-07-26 17:27:00,352 ERROR      File "/public/home/xkang12/software/miniconda3/envs/py2/bin/hap.py", line 225, in main
2022-07-26 17:27:00,352 ERROR        raise Exception("The output path should specify a file name prefix. Please specify a valid output path "
2022-07-26 17:27:00,352 ERROR    Exception: The output path should specify a file name prefix. Please specify a valid output path and prefix using -o. For example, -o /tmp/test will create files named /tmp/test* .

**Comment by b-math** [comment]
Hi, you can set the path to your reference genome fasta file (replace "$ref_genome_path" by your path):
`export HGREF=$ref_genome_path`
If you run your command afterwards, it should work.
There is also the possibility to save your reference genome in a default location, so you dont have to set the path anew in each new bash. But I don't recall the folder right now.

Best regards
Barbara
