### ISSUE TITLE
Hap.py not working with singularity

### ISSUE THREAD

**Issue by NoamYakar23** [Illumina/hap.py#164]
I ran hap.py in an interactive shell with singularity here are the commands I used

I can't install any modules as I am running this on an HPC environment

interactive

module load singularity/3.8.0

singularity run --env HGREF=/scratch/nyakar/Parabricks/Parabricks/hg38/hg38_all_sequences.fa --bind /scratch/nyakar/Parabricks:/home  /scratch/nyakar/Parabricks/Parabricks/hap.py_latest.sif

/opt/hap.py/bin/hap.py -r ./hg38/hg38_all_sequences.fa  --report-prefix happy.output   --engine=vcfeval   --threads 10 GIAB-Ash-002A_germline.vcf.gz HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz -f Exome-IDT_V1V2_span50bp.bed

**This is the error I got**

zero exit status 1
2022-08-25 09:32:46,464 ERROR    Traceback (most recent call last):
2022-08-25 09:32:46,465 ERROR      File "/opt/hap.py/bin/hap.py", line 508, in <module>
2022-08-25 09:32:46,469 ERROR        main()
2022-08-25 09:32:46,469 ERROR      File "/opt/hap.py/bin/hap.py", line 493, in main
2022-08-25 09:32:46,469 ERROR        qfy.quantify(args)
2022-08-25 09:32:46,470 ERROR      File "/opt/hap.py/bin/qfy.py", line 129, in quantify
2022-08-25 09:32:46,472 ERROR        strat_fixchr=args.strat_fixchr)
2022-08-25 09:32:46,472 ERROR      File "/opt/hap.py/lib/python27/Haplo/quantify.py", line 178, in run_quantify
2022-08-25 09:32:46,474 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2022-08-25 09:32:46,474 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2022-08-25 09:32:46,479 ERROR        raise CalledProcessError(retcode, cmd)
2022-08-25 09:32:46,480 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.APmoAD.vcf.gz -o happy.output.roc.tsv -r ./hg38/hg38_all_sequences.fa --threads 10 --output-vtc 0 --output-rocs 1 --type ga4gh --qq QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v happy.output.vcf.gz -R 'CONF_VARS:/tmp/tmpoV04WZ.bed' -R 'CONF:Exome-IDT_V1V2_span50bp.bed' --roc-regions '*'' returned non-zero exit status 1

Not really sure what the issue is

**Comment by cwarden45** [comment]
I am successfully running _hap.py_ on Singularity (or I am at least not receiving error messages).

I this in a two-step process (where the first command is only used once):

```
singularity pull docker://pkrusche/hap.py
singularity exec --bind $MOUNTIN:$MOUNTOUT hap.py_latest.sif /opt/hap.py/bin/hap.py $REF $TEST -f $BED -o $OUT -r $FA
```

Subfolders within $MOUNTIN directly appear within /mnt (which is $MOUNTOUT).

**Does this help with running _hap.py_ on Singularity?**
