### ISSUE TITLE
How to call hap,.py with vcfeval for joint vcf.

### ISSUE THREAD

**Issue by sanketshah11** [Illumina/hap.py#17]
How do I provide sample name on the command line of HAP.py to run vcfeval for multi-sample vcf

Here is the error I get currently:

2017-05-11 21:35:33,701 ERROR    Error running rtg tools / vcfeval. Return code was 1, output:  / Error: No sample name provided but calls is a multi-sample VCF.

2017-05-11 21:35:33,702 ERROR    Traceback (most recent call last):
2017-05-11 21:35:33,702 ERROR      File "/opt/hap.py/bin/hap.py", line 417, in <module>
2017-05-11 21:35:33,702 ERROR        main()
2017-05-11 21:35:33,702 ERROR      File "/opt/hap.py/bin/hap.py", line 394, in main
2017-05-11 21:35:33,702 ERROR        tempfiles += Haplo.vcfeval.runVCFEval(args.vcf1, args.vcf2, output_name, args)
2017-05-11 21:35:33,702 ERROR      File "/opt/hap.py/lib/python27/Haplo/vcfeval.py", line 136, in runVCFEval
2017-05-11 21:35:33,703 ERROR        raise Exception("Error running rtg tools / vcfeval. Return code was %i, output: %s / %s \n" % (rc, o, e))
2017-05-11 21:35:33,703 ERROR    Exception: Error running rtg tools / vcfeval. Return code was 1, output:  / Error: No sample name provided but calls is a multi-sample VCF.

**Comment by pkrusche** [comment]
Hap.py doesn't directly support multi-sample VCFs. You can extract the sample that you would like to compare using bcftools:

```
bcftools view -s <SAMPLE_TO_USE> <MULTI-SAMPLE-INPUT.VCF> -o <OUTPUT.VCF.GZ> -O z
```

Then you should be able to run hap.py with vcfeval on OUTPUT.VCF.GZ.

**Comment by sanketshah11** [comment]
Thanks Peter. That was helpful.

**Comment by tlqtangok** [comment]
```
my real world usage of bcftools is : 

> cat draw_hg002.sample 
hg002

>bcftools view -S -s draw_hg002.sample hg002_hg003_hg004_merge_annotated.vcf.gz > hg002_hg003_hg004_merge_annotated_draw_hg002.vcf

```

hope it helps!
