### ISSUE TITLE
[E::bgzf_uncompress] inflate failed: invalid distance too far back

### ISSUE THREAD

**Issue by liukeweiaway** [Illumina/hap.py#185]
The error log file as:
[E::bgzf_uncompress] inflate failed: invalid distance too far back
[E::bgzf_read_block] inflate_block error -1
Number of samples in line and header disagrees at chr2:131765544
2023-12-13 10:11:49,962 ERROR    Command 'vcfcheck /lustre/home/acct-medfzx/medfzx-lkw/project/CAH/data/database/pangenome/graph/GRCH38/benchmark/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz --check-bcf-errors 1' returned non-zero exit status 1
2023-12-13 10:11:49,962 ERROR    Traceback (most recent call last):
2023-12-13 10:11:49,963 ERROR      File "/opt/hap.py/bin/hap.py", line 529, in <module>
2023-12-13 10:11:49,963 ERROR        main()
2023-12-13 10:11:49,963 ERROR      File "/opt/hap.py/bin/hap.py", line 309, in main
2023-12-13 10:11:49,964 ERROR        convert_gvcf_to_vcf=args.convert_gvcf_truth)
2023-12-13 10:11:49,964 ERROR      File "/opt/hap.py/bin/pre.py", line 125, in preprocess
2023-12-13 10:11:49,964 ERROR        mf = subprocess.check_output("vcfcheck %s --check-bcf-errors 1" % pipes.quote(vcf_input), shell=True)
2023-12-13 10:11:49,964 ERROR      File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
2023-12-13 10:11:49,967 ERROR        raise CalledProcessError(retcode, cmd, output=output)
2023-12-13 10:11:49,967 ERROR    CalledProcessError: Command 'vcfcheck /lustre/home/acct-medfzx/medfzx-lkw/project/CAH/data/database/pangenome/graph/GRCH38/benchmark/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz --check-bcf-errors 1' returned non-zero exit status 1

what can i do to solve it.

**Comment by 12138YQH** [comment]
Dear Author,

I am currently facing a similar issue to the one you described regarding the missing contig definitions in the VCF file header. I have attempted to follow the usual steps, but the problem persists, and I keep encountering warnings and errors related to undefined contigs.

I came across your solution on this matter and was wondering if you could kindly share the detailed steps you took to resolve this issue. Your expertise and guidance would be immensely helpful to me in overcoming this challenge.

Thank you very much for your time and assistance.

Best regards,
