### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by MAlwaz** [Illumina/hap.py#186]
Hello,
I followed the documentation and tried running the comparison on the example files got this error:

```
(happy) meshari@MacBook-Pro-3 hap.py-master % sudo docker run -it -v pwd:/data 47b2428b563f /opt/hap.py/bin/hap.py /data/example/PG_performance.vcf.gz /data/example/performance.vcf.gz -o /data/test
Password:
2024-04-22 12:58:54,346 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
Hap.py 
2024-04-22 12:58:54,509 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2024-04-22 12:58:54,509 ERROR    Please specify a valid reference path using -r.
2024-04-22 12:58:54,509 ERROR    Traceback (most recent call last):
2024-04-22 12:58:54,509 ERROR      File "/opt/hap.py/bin/hap.py", line 540, in <module>
2024-04-22 12:58:54,510 ERROR        main()
2024-04-22 12:58:54,510 ERROR      File "/opt/hap.py/bin/hap.py", line 216, in main
2024-04-22 12:58:54,510 ERROR        raise Exception("Please specify a valid reference path using -r.")
2024-04-22 12:58:54,510 ERROR    Exception: Please specify a valid reference path using -r.
```

I used the following steps

```
git clone https://github.com/Illumina/hap.py.git

cd hap.py

sudo docker run -it -v ⁠ pwd ⁠:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/example/PG_performance.vcf.gz /data/example/performance.vcf.gz -o /data/test
```

I also tried installing the tool locally using 

```
python install.py ~/hap.py-install

```
but encountered this error 

```
(happy) meshari@MacBook-Pro-3 hap.py-master % python install.py ~/hap.py-install
cd /tmp/build0CMaVy &&  /Users/meshari/Desktop/Hap/hap.py-master/configure.sh Release auto /Users/meshari/hap.py-install
Build from /Users/meshari/Desktop/Hap/hap.py-master, type is Release / installation directory: /Users/meshari/hap.py-install
Using system Boost
/Users/meshari/Desktop/Hap/hap.py-master/configure.sh: line 111: cmake: command not found
cd /tmp/build0CMaVy &&  make -j16
make: *** No targets specified and no makefile found.  Stop.
Traceback (most recent call last):
  File "install.py", line 298, in <module>
    main()
  File "install.py", line 283, in main
    build_haplotypes(source_dir, build_dir, args)
  File "install.py", line 157, in build_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/Users/meshari/anaconda3/envs/happy/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /tmp/build0CMaVy &&  make -j16' returned non-zero exit status 2
```
It will be great to be able to use the tools. Looking forward to hear from you soon.
Thank you.
Regards

**Comment by lsy356** [comment]
> /Users/meshari/Desktop/Hap/hap.py-master/configure.sh: line 111: cmake: command not found

Install cmake
