### ISSUE TITLE
While using hap.py, there is a problem: 

### ISSUE THREAD

**Issue by pioneer-pi** [Illumina/hap.py#189]
I use docker to start hap.py.
The docker sentences:
```
docker run -it \
  -v "${PWD}":"/input" \
  -v "${PWD}/my_output:/output" \
  jmcdani20/hap.py:v0.3.12 /opt/hap.py/bin/hap.py \
  /input/chr20.vcf.gz \
  /output/my.vcf \
  -f "/input/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_chr.bed" \
  -r "/input/ucsc_hg19.fa" \
  -o "/output/happy.output" \
  --engine=vcfeval \
  --pass-only \
  -l chr20
```
The error information is :
```
2024-07-13 12:29:32,677 WARNING  Creating template for vcfeval. You can speed this up by supplying a SDF template that corresponds to /input/ucsc_hg19.fa
2024-07-13 12:30:43,939 ERROR    Error running rtg tools / vcfeval. Return code was 1, output:  / null
Error: RTG has encountered a difficulty, please contact support@realtimegenomics.com
Please send the log file ('/tmp/vcfeval.result3BAEs0.dir/vcfeval.log') to Real Time Genomics at rtg-talkback@realtimegenomics.com
 

2024-07-13 12:30:43,939 ERROR    Traceback (most recent call last):
2024-07-13 12:30:43,939 ERROR      File "/opt/hap.py/bin/hap.py", line 529, in <module>
2024-07-13 12:30:43,939 ERROR        main()
2024-07-13 12:30:43,939 ERROR      File "/opt/hap.py/bin/hap.py", line 473, in main
2024-07-13 12:30:43,939 ERROR        tempfiles += Haplo.vcfeval.runVCFEval(args.vcf1, args.vcf2, output_name, args)
2024-07-13 12:30:43,939 ERROR      File "/opt/hap.py/lib/python27/Haplo/vcfeval.py", line 132, in runVCFEval
2024-07-13 12:30:43,940 ERROR        raise Exception("Error running rtg tools / vcfeval. Return code was %i, output: %s / %s \n" % (rc, o, e))
2024-07-13 12:30:43,940 ERROR    Exception: Error running rtg tools / vcfeval. Return code was 1, output:  / nullError: RTG has encountered a difficulty, please contact support@realtimegenomics.comPlease send the log file ('/tmp/vcfeval.result3BAEs0.dir/vcfeval.log') to Real Time Genomics at rtg-talkback@realtimegenomics.com
```

**Comment by djwight** [comment]
Hey @pioneer-pi ,
Late reply, but maybe others will end up here... 😃 

I ran into a similar issue to the one you mentioned, when when running `hap.py` commands in a docker container using the `vcfeval` engine. 
I found the source of the error was coming from running any `rtg` command in the running docker container, which returned `null` and a non-descriptive error `Error: RTG has encountered a difficulty, please contact support@realtimegenomics.com` 😅 

I was able to resolve this by **not** installing RTG with hap.py and instead installing it separately during buildtime. Below is my reconfigured `Dockerfile` that enabled me to use `hapy.py` with the `vcfeval` engine.

Hope that helps!

```Dockerfile
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    autoconf \
    build-essential \
    bzip2 \
    cmake \
    cython \
    git \
    libbz2-dev \
    libncurses5-dev \
    openjdk-8-jdk \
    pkg-config \                    
    python \
    python2.7 \
    python2.7-dev \                    
    python-setuptools \
    python-pip \
    python-psutil \                    
    python-numpy \
    python-pandas \
    python-distribute \
    python-pysam \
    python-scipy \                    
    software-properties-common \
    wget \
    unzip \
    zlib1g-dev && \
    apt-get clean -y

RUN pip install bx-python

# copy git repository into the image
RUN wget https://github.com/Illumina/hap.py/archive/refs/tags/v0.3.15.tar.gz && \
    tar -xzvf v0.3.15.tar.gz && \
    rm v0.3.15.tar.gz
RUN mkdir -p /opt/hap.py-source && \
    cp -r /hap.py-0.3.15/* /opt/hap.py-source

# make minimal HG19 reference sequence
RUN mkdir -p /opt/hap.py-data

# download HG19 reference data
WORKDIR /opt/hap.py-data

# get + install ant
WORKDIR /opt
RUN wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.7-bin.tar.gz && \
    tar xzf apache-ant-1.9.7-bin.tar.gz && \
    rm apache-ant-1.9.7-bin.tar.gz
ENV PATH=$PATH:/opt/apache-ant-1.9.7/bin

# run hap.py installer in the image, don't run tests since we don't have a reference file
WORKDIR /opt/hap.py-source
RUN python install.py /opt/hap.py --no-tests
WORKDIR /opt/hap.py

# install fresh RTG tools
RUN wget https://github.com/RealTimeGenomics/rtg-tools/releases/download/3.13/rtg-tools-3.13-linux-x64.zip && \
    unzip rtg-tools-3.13-linux-x64.zip && \
    rm rtg-tools-3.13-linux-x64.zip
RUN mkdir -p /opt/hap.py/libexec/rtg-tools-install && \
    mv /opt/hap.py/rtg-tools-3.13/* /opt/hap.py/libexec/rtg-tools-install/ 

# configure RTG tools and create symlink to /usr/local/bin (needed for hap.py!)
RUN echo 'n' | /opt/hap.py/libexec/rtg-tools-install/rtg help
RUN ln -s /opt/hap.py/libexec/rtg-tools-install/rtg /usr/local/bin/

# run basic tests
RUN bin/test_haplotypes

# remove source folder
WORKDIR /
RUN rm -rf /opt/hap.py-source && \
    rm -rf /hap.py-0.3.15
```
