### ISSUE TITLE
sudo docker build .

### ISSUE THREAD

**Issue by avilella** [Illumina/hap.py#2]
```
[...]
*** 2391 failures detected in test suite "Master Test Suite"
Boost Unit tests FAILED!
Traceback (most recent call last):
  File "install.py", line 315, in <module>
    main()
  File "install.py", line 311, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 191, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /opt/hap.py && /opt/hap.py-source/src/sh/run_tests.sh' returned non-zero exit status 1
The command '/bin/sh -c HG19=/opt/hap.py-data/hg19.fa python install.py /opt/hap.py' returned a non-zero code: 1
```

Any ideas?

**Comment by pkrusche** [comment]
I have not seen this before. Could you maybe paste the output from running `bin/test_haplotypes`? 

Thanks!

**Comment by avilella** [comment]
This is at the `sudo docker build .` step, so no binaries exist outside docker:
From the `Dockerfile` steps:
```
# run hap.py installer in the image
WORKDIR /opt/hap.py-source
RUN HG19=/opt/hap.py-data/hg19.fa python install.py /opt/hap.py
WORKDIR /
RUN rm -rf /opt/hap.py-source
```

```
~/hap.py$ ls -l ./bin/
ls: cannot access ./bin/: No such file or directory
```

**Comment by pkrusche** [comment]
Could you check inside the container? You can get a shell using 

```
docker run -it -d <container name> bin/bash
```

To find the container name, the most recent one from here should be it:

```
sudo docker ps -a
```

Another possible fix might be to clear the Docker cache, restart the daemon, and build again? Sometimes Docker loses its network connection, and the Docker installation process needs access to the internet.

**Comment by avilella** [comment]
I tried a couple more times, it consistently complains about `Boost Unit tests FAILED!`:

```
Testing Ksw performance for Haplotype comparison.

size    klib    klibg
128     39712.3 192837
192     142299  424609
256     265642  742147
320     418948  1.15442e+06
384     655086  1.64458e+06
448     211312  2.23166e+06
512     1.75529e+06     2.88694e+06


*** 2391 failures detected in test suite "Master Test Suite"
Boost Unit tests FAILED!
Traceback (most recent call last):
  File "install.py", line 315, in <module>
    main()
  File "install.py", line 311, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 191, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /opt/hap.py && /opt/hap.py-source/src/sh/run_tests.sh' returned non-zero exit status 1
The command '/bin/sh -c HG19=/opt/hap.py-data/hg19.fa python install.py /opt/hap.py' returned a non-zero code: 1
```

Then running the container only shows the data and source directories, no bin:

```
~/hap.py$ sudo docker run -it 20b5053dd999 /bin/bash
root@f18ed958b5d4:/opt/hap.py-source# cd /opt
root@f18ed958b5d4:/opt# ls -l
total 8
drwxr-xr-x 2 root root 4096 Dec  1 11:08 hap.py-data
drwxr-xr-x 7 root root 4096 Dec  1 11:05 hap.py-source
```

**Comment by pkrusche** [comment]
Does this file exist inside the image: `/opt/hap.py-data/hg19.fa` ? Also, is it a valid hg19 reference sequence, and is it indexed? 

To see which unit tests fail, this should work inside the Docker image:

```
cd /opt
mkdir hap.py-build
cd hap.py-build
../hap.py-source/configure.sh Release
make
bin/test_haplotypes &> test.log
```

Could you send the full output from test.log?

Thanks!

**Comment by pkrusche** [comment]
Also, which Docker version are you using?

I have re-run the Dockerfile from scratch here, and cannot reproduce the issue.

**Comment by avilella** [comment]
Find below:
```
ls -l /opt/hap.py-data/hg19.fa*


-rw-r--r-- 1 root root 3157608038 Dec  1 11:08 /opt/hap.py-data/hg19.fa
-rw-r--r-- 1 root root        788 Dec  1 11:08 /opt/hap.py-data/hg19.fa.fai
```

**Comment by avilella** [comment]
This is running on an Ubuntu 14.04 machine, with docker 1.9.1:
```
avilella@gonzo:~/hap.py$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
avilella@gonzo:~/hap.py$ docker --version
Docker version 1.9.1, build a34a1d5
```

**Comment by pkrusche** [comment]
I have tried with this version of Docker (on Ubuntu 15.04), and was not able to reproduce the error.

The two things that I think are worth trying would be:

* re-run the Docker build with a fresh clone of the repository (clearing out all containers / images before)
* using the configure / make commands above inside the Docker image, find out which tests exactly are failing.

**Comment by avilella** [comment]
Attached log file.

**Comment by pkrusche** [comment]
The failure is unrelated to the reference sequence, but hard to diagnose without debugging it. Let's see if the automated build in #3 works out.

**Comment by pkrusche** [comment]
Ok, the automated build is now available at https://hub.docker.com/r/pkrusche/hap.py/

To see if the tests are still failing, you can try this:

```bash
sudo docker pull pkrusche/hap.py
cd <hap.py-checkout-dir>
sudo docker run -it -v `pwd`:/opt/hap.py-source pkrusche/hap.py bin/bash
# ... shell is now in Docker container
cd /opt/hap.py
export HG19=/opt/hap.py-data/hg19.fa
/opt/hap.py-source/src/sh/run_tests.sh
```

... for me, this seems to work fine.
