### ISSUE TITLE
install failed at Ubuntu 16.04,  'DataFrame' object has no attribute 'sort'

### ISSUE THREAD

**Issue by jq2252** [Illumina/hap.py#20]
I try to install at Ubuntu 16.04, and install all depencies in the dockerfile.
With numexpr is 2.6.2 and pandas 0.20.3,numpy 1.13.1
The install is failed ruing the test file, the related log is as following. Does it because som.py used deperated 
 method sort which is not supported by the pandas?:
```
/usr/bin/python /home/jianfeng.qian/hap.py-install/bin/som.py /home/jianfeng.qian/graph_geno/hap.py/src/sh/../../example/sompy/PG_admix_truth_snvs.vcf.gz /home/jianfeng.qian/graph_geno/hap.py/src/sh/../../example/sompy/strelka_admix_snvs.vcf.gz -o /tmp/sompy.L2qFyDafe7 -P --feature-table hcc.strelka.indel
2017-07-14 02:58:03,424 WARNING  Missing feature I.QSI_NT
2017-07-14 02:58:03,429 WARNING  Missing feature I.RC
2017-07-14 02:58:03,430 WARNING  Missing feature I.IC
2017-07-14 02:58:03,430 WARNING  Missing feature I.IHP
2017-07-14 02:58:03,430 WARNING  Missing feature S.1.BCN50
2017-07-14 02:58:03,430 WARNING  Missing feature S.2.BCN50
2017-07-14 02:58:03,430 WARNING  Missing feature S.1.FDP50
2017-07-14 02:58:03,431 WARNING  Missing feature S.2.FDP50
2017-07-14 02:58:03,431 WARNING  Missing feature S.1.TAR
2017-07-14 02:58:03,431 WARNING  Missing feature S.2.TAR
2017-07-14 02:58:03,431 WARNING  Missing feature S.1.TIR
2017-07-14 02:58:03,431 WARNING  Missing feature S.2.TIR
2017-07-14 02:58:03,432 WARNING  Missing feature S.1.TOR
2017-07-14 02:58:03,432 WARNING  Missing feature S.2.TOR
2017-07-14 02:58:17,032 ERROR    'DataFrame' object has no attribute 'sort'
2017-07-14 02:58:17,038 ERROR    Traceback (most recent call last):
2017-07-14 02:58:17,038 ERROR      File "/home/jianfeng.qian/hap.py-install/bin/som.py", line 779, in <module>
2017-07-14 02:58:17,038 ERROR        main()
2017-07-14 02:58:17,038 ERROR      File "/home/jianfeng.qian/hap.py-install/bin/som.py", line 500, in main
2017-07-14 02:58:17,039 ERROR        tps.sort(["CHROM", "POS"], inplace=True)
2017-07-14 02:58:17,039 ERROR      File "/usr/local/lib/python2.7/dist-packages/pandas-0.20.3-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 3081, in __getattr__
2017-07-14 02:58:17,041 ERROR        return object.__getattribute__(self, name)
2017-07-14 02:58:17,041 ERROR    AttributeError: 'DataFrame' object has no attribute 'sort'
som.py failed!
Som.py test FAILED!
Traceback (most recent call last):
  File "install.py", line 325, in <module>
    main()
  File "install.py", line 321, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 190, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/jianfeng.qian/hap.py-install && /home/jianfeng.qian/graph_geno/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1
```

**Comment by pkrusche** [comment]
Fixed in v0.3.10
