### ISSUE TITLE
gvcf2bed issue

### ISSUE THREAD

**Issue by keyvanelhami** [Illumina/hap.py#23]
Hi,

I have installed hap.py through bioconda and I tried to run the program according to the read me document:

```
hap.py hap.py/example/happy/PG_NA12878_chr21.vcf.gz hap.py/example/happy/NA12878_chr21.vcf.gz -r /mnt/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -f hap.py/example/happy/PG_Conf_chr21.bed.gz -o test
```
I got the following error: 

```
2017-09-04 14:10:07,886 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-09-04 14:10:07,897 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[W] overlapping records at chr21:10993857 for sample 0
[W] Symbolic / SV ALT alleles at chr21:15847469
[W] Variants that overlap on the reference allele: 144
[W] Variants that have symbolic ALT alleles: 14
[I] Total VCF records:         65402
[I] Non-reference VCF records: 65402
Contig chr21 is not known
2017-09-04 14:10:21,531 ERROR    Command 'gvcf2bed /tmp/truth.ppCDsZ5w.vcf.gz -r /mnt/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -o /tmp/tmpqpBTVv.bed -T hap.py/example/happy/PG_Conf_chr21.bed.gz' returned non-zero exit status 1
2017-09-04 14:10:21,531 ERROR    Traceback (most recent call last):
2017-09-04 14:10:21,531 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/bin/hap.py", line 460, in <module>
2017-09-04 14:10:21,532 ERROR        main()
2017-09-04 14:10:21,532 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/bin/hap.py", line 282, in main
2017-09-04 14:10:21,532 ERROR        conf_temp = Haplo.gvcf2bed.gvcf2bed(args.vcf1, args.ref, args.fp_bedfile, args.scratch_prefix)
2017-09-04 14:10:21,532 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/lib/python27/Haplo/gvcf2bed.py", line 38, in gvcf2bed
2017-09-04 14:10:21,544 ERROR        subprocess.check_call(cmdline, shell=True)
2017-09-04 14:10:21,545 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/lib/python2.7/subprocess.py", line 186, in check_call
2017-09-04 14:10:21,561 ERROR        raise CalledProcessError(retcode, cmd)
2017-09-04 14:10:21,561 ERROR    CalledProcessError: Command 'gvcf2bed /tmp/truth.ppCDsZ5w.vcf.gz -r /mnt/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -o /tmp/tmpqpBTVv.bed -T hap.py/example/happy/PG_Conf_chr21.bed.gz' returned non-zero exit status 1
```
I downloaded gvcf2bed and tried to run the same command again and got a new error.

```
2017-09-04 14:25:11,100 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-09-04 14:25:11,104 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[W] overlapping records at chr21:10993857 for sample 0
[W] Symbolic / SV ALT alleles at chr21:15847469
[W] Variants that overlap on the reference allele: 144
[W] Variants that have symbolic ALT alleles: 14
[I] Total VCF records:         65402
[I] Non-reference VCF records: 65402
usage: gvcf2bed [-h] -I INPUT -O OUTPUT [-s SAMPLE] [-q QUALITY]
                [-nq NON_VARIANT_QUALITY] [-b]
gvcf2bed: error: argument -I/--input is required
2017-09-04 14:25:12,072 ERROR    Command 'gvcf2bed /tmp/truth.ppfH1zZb.vcf.gz -r /mnt/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -o /tmp/tmpCeSiNo.bed -T hap.py/example/happy/PG_Conf_chr21.bed.gz' returned non-zero exit status 2
2017-09-04 14:25:12,072 ERROR    Traceback (most recent call last):
2017-09-04 14:25:12,072 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/bin/hap.py", line 460, in <module>
2017-09-04 14:25:12,072 ERROR        main()
2017-09-04 14:25:12,073 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/bin/hap.py", line 282, in main
2017-09-04 14:25:12,073 ERROR        conf_temp = Haplo.gvcf2bed.gvcf2bed(args.vcf1, args.ref, args.fp_bedfile, args.scratch_prefix)
2017-09-04 14:25:12,073 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/lib/python27/Haplo/gvcf2bed.py", line 38, in gvcf2bed
2017-09-04 14:25:12,073 ERROR        subprocess.check_call(cmdline, shell=True)
2017-09-04 14:25:12,073 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/lib/python2.7/subprocess.py", line 186, in check_call
2017-09-04 14:25:12,074 ERROR        raise CalledProcessError(retcode, cmd)
2017-09-04 14:25:12,074 ERROR    CalledProcessError: Command 'gvcf2bed /tmp/truth.ppfH1zZb.vcf.gz -r /mnt/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -o /tmp/tmpCeSiNo.bed -T hap.py/example/happy/PG_Conf_chr21.bed.gz' returned non-zero exit status 2
```

It seems like gvcf2bed only supports in python 3 but I was unable to install hap.py in python 3. This probably isn't causing the error but which python version you recommend to run hap.py?

**Comment by pkrusche** [comment]
Hap.py requires Python 2.7 and will not work in Python 3.

gvcf2bed is a C++ tool that is included with hap.py, no additional download / external tool is required.

The problem here is trying to use a GRCh37 reference fasta with hg19 VCF files. Gvcf2bed cannot find contig chr21 in the reference, presumably because the reference contains this contig using the name '21'.

This script downloads and makes an appropriate reference file: https://github.com/Illumina/hap.py/blob/master/src/sh/make_hg19.sh

Also, the reference FASTA should always be the same that was used both for truth and query VCF. The only exception is that hap.py can work with is if the truth files are all hg19 (including the reference fasta, all having a chr prefix on their contig names), and only the query is GRCh37 (and has no chr prefix). This is a workaround we have implemented for using Platinum Genomes as a truthset for GRCh37 -- it should probably not be used elsewhere.

**Comment by pkrusche** [comment]
Also, we will document the requirements for Python versions better in the next release -- checking the documentation, I agree that the dependency isn't very clear at the moment.

**Comment by keyvanelhami** [comment]
Thank you for the answer. I downloaded and did index the hg19 reference, but I got the same kind of error with "gvc2bed". I believe that there is some problem with the downloading hap.py through bioconda.

However, I tried to reinstall hap.py using the instructions in "readme" document:
python install.py ~/hap.py-install

And I got an error which I need help to solve:

```
2017-09-06 11:06:46,094 ERROR    [stderr] regex_error
2017-09-06 11:06:46,102 ERROR    Command 'quantify /tmp/hap.py.result.V2dyS0.vcf.gz -o test_happy.roc.tsv -r /mnt/hds/proj/bioinfo/develop/modules/hg19.fa --threads 16 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test_happy.vcf.gz -R 'CONF_VARS:/tmp/tmpKFprlI.bed' -R 'CONF:hap.py/example/happy/PG_Conf_chr21.bed.gz' --roc-regions '*'' returned non-zero exit status 1
2017-09-06 11:06:46,102 ERROR    Traceback (most recent call last):
2017-09-06 11:06:46,102 ERROR      File "/home/hiseq.clinical/hap.py-install/bin/hap.py", line 511, in <module>
2017-09-06 11:06:46,102 ERROR        main()
2017-09-06 11:06:46,102 ERROR      File "/home/hiseq.clinical/hap.py-install/bin/hap.py", line 496, in main
2017-09-06 11:06:46,102 ERROR        qfy.quantify(args)
2017-09-06 11:06:46,102 ERROR      File "/home/hiseq.clinical/hap.py-install/bin/qfy.py", line 129, in quantify
2017-09-06 11:06:46,103 ERROR        strat_fixchr=args.strat_fixchr)
2017-09-06 11:06:46,103 ERROR      File "/home/hiseq.clinical/hap.py-install/lib/python27/Haplo/quantify.py", line 178, in run_quantify
2017-09-06 11:06:46,103 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2017-09-06 11:06:46,103 ERROR      File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/rnaseq/lib/python2.7/subprocess.py", line 186, in check_call
2017-09-06 11:06:46,104 ERROR        raise CalledProcessError(retcode, cmd)
2017-09-06 11:06:46,104 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.V2dyS0.vcf.gz -o test_happy.roc.tsv -r /mnt/hds/proj/bioinfo/develop/modules/hg19.fa --threads 16 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test_happy.vcf.gz -R 'CONF_VARS:/tmp/tmpKFprlI.bed' -R 'CONF:hap.py/example/happy/PG_Conf_chr21.bed.gz' --roc-regions '*'' returned non-zero exit status 1
```

**Comment by pkrusche** [comment]
The reason for this error is probably that a too old version of g++ was used to build quantify. Hap.py must be compiled with g++ version 4.9.2 or newer, 4.8 has bugs in the STL Regex support.

**Comment by pkrusche** [comment]
See also the second half of #13
