### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by splaisan** [Illumina/hap.py#25]
Install fails as shown below, do you have any idea what is wrong?
the dependencies are all installes and I ran
`sudo -H python install.py ~/hap.py-install`

I could later install with the 'make 'method but do not quite understand the need of the initial and failed install.

Thanks for your feedback
```
...
Skipping Locations.INDEL -- not present on both sides
Chr prefixed truth test successful
Chr prefix detection tests SUCCEEDED!
2017-10-29 10:25:42,256 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-10-29 10:25:42,257 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
Variant decomposition test Hap.py v0.3.10 from /home/luna.kuleuven.be/u0002316/hap.py-install/bin
2017-10-29 10:25:42,827 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-10-29 10:25:42,828 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-10-29 10:25:42,975 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-10-29 10:25:42,976 ERROR    Please specify a valid reference path using -r.
2017-10-29 10:25:42,976 ERROR    Traceback (most recent call last):
2017-10-29 10:25:42,976 ERROR      File "/home/luna.kuleuven.be/u0002316/hap.py-install/bin/hap.py", line 511, in <module>
2017-10-29 10:25:42,976 ERROR        main()
2017-10-29 10:25:42,976 ERROR      File "/home/luna.kuleuven.be/u0002316/hap.py-install/bin/hap.py", line 211, in main
2017-10-29 10:25:42,976 ERROR        raise Exception("Please specify a valid reference path using -r.")
2017-10-29 10:25:42,976 ERROR    Exception: Please specify a valid reference path using -r.
hap.py failed!
Variant decomposition test FAILED!
Traceback (most recent call last):
  File "install.py", line 298, in <module>
    main()
  File "install.py", line 294, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 170, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/luna.kuleuven.be/u0002316/hap.py-install && /opt/biotools/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1
```

**Comment by pkrusche** [comment]
To run all tests successfully you need to require a hg19 reference FASTA file. If you don't have one, this script downloads it: https://github.com/Illumina/hap.py/blob/master/src/sh/make_hg19.sh 

Before running install.py, point hap.py to this file as follows:

```
export HGREF=<path-to-your-hg19.fa>
export HG19=<path-to-your-hg19.fa>

python install.py ~/hap.py-install
```

Also I don't think you'll need sudo permissions to install into your home directory if all Python requirements are installed already.

Hope this helps!

**Comment by splaisan** [comment]
Thanks Peter, you were right, it now worked out (stupid sudo error of mine)

BTW, can I use hap.py with a more recent reference?
Should I simply point the two ref variables to it or is there something in hap.py that is specific to hg19.
I had in mind the latest ensembl  GRCh38.p10 with all KIXXXXXX.1 records.
Thanks

**Comment by pkrusche** [comment]
The environment variables are only needed for running the subset of the tests that are based on hg19.

When running an installed version of hap.py you may point it to any reference Fasta using the `-r` command line option. Note that the reference Fasta file must match the truth and query VCFs, as well as all other bed files that were passed, otherwise errors may occur.

Both [Platinum Genomes](https://github.com/Illumina/PlatinumGenomes) and [Genome in a Bottle](http://jimb.stanford.edu/giab/) provide separate hg38 reference files, either should be fine to use with hap.py.
