### ISSUE TITLE
regex error despite using gcc 4.9

### ISSUE THREAD

**Issue by patrickturko** [Illumina/hap.py#28]
I'm running hap.py like this: 

    hap.py patient_3_strelka.vcf.gz patient_3_varscan.vcf.gz --reference /b37/human_g1k_v37.fasta -o ${NAME}_str_var

My input vcfs are sorted, bgzipped, and tabix indexed.

I'm running it on a 64 core server with 500GB RAM. It's running CentOS Linux release 7.3.1611. 

Gcc is version 4.9.2. I upgraded from 4.8 this morning; after upgrading gcc I uninstalled and re-installed hap.py using Bioconda. 

It runs for a while and then produces the following error messages: 

2017-11-17 14:18:42,736 ERROR    Command 'quantify /tmp/4487.1.all.q/hap.py.result.WAYuiy.vcf.gz -o _str_var.roc.tsv -r /b37/human_g1k_v37.fasta --threads 64 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v _str_var.vcf.gz --roc-regions '\*'' returned non-zero exit status 1
2017-11-17 14:18:42,736 ERROR    Traceback (most recent call last):
2017-11-17 14:18:42,736 ERROR      File "/home/wid/miniconda3/envs/patrick/bin/hap.py", line 460, in <module>
2017-11-17 14:18:42,737 ERROR        main()
2017-11-17 14:18:42,737 ERROR      File "/home/wid/miniconda3/envs/patrick/bin/hap.py", line 445, in main
2017-11-17 14:18:42,737 ERROR        qfy.quantify(args)
2017-11-17 14:18:42,737 ERROR      File "/home/wid/miniconda3/envs/patrick/bin/qfy.py", line 129, in quantify
2017-11-17 14:18:42,737 ERROR        strat_fixchr=args.strat_fixchr)
2017-11-17 14:18:42,737 ERROR      File "/home/wid/miniconda3/envs/patrick/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2017-11-17 14:18:42,738 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2017-11-17 14:18:42,738 ERROR      File "/home/wid/miniconda3/envs/patrick/lib/python2.7/subprocess.py", line 186, in check_call
2017-11-17 14:18:42,738 ERROR        raise CalledProcessError(retcode, cmd)
2017-11-17 14:18:42,739 ERROR    CalledProcessError: Command 'quantify /tmp/4487.1.all.q/hap.py.result.WAYuiy.vcf.gz -o _str_var.roc.tsv -r /data/Phil/ref_phil/GATK_resource/b37/human_g1k_v37.fasta --threads 64 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v _str_var.vcf.gz --roc-regions '*'' returned non-zero exit status 1

This seems to have something to do with the ROCs. I added the --no.roc flag to the command, but it failed the same way.

**Comment by patrickturko** [comment]
I added the --no.roc flag to the command, but it failed the same way.

**Comment by pkrusche** [comment]
Is gcc 4.9 the default compiler? It is possible that Bioconda still uses an older version?

The regex code that is part of ROC calculation gets executed also when ROCs are off (it's part of hap.py's counting mechanism -- no ROC is handled as calculating a ROC with only the endpoint s.t. counting is consistent between ROC and summary metrics.

It might be worth trying to build hap.py from source using the instructions here: https://github.com/illumina/hap.py#compiling-from-source-with-cmake -- these allow you to specify the compiler binaries to use explicitly + produce a build log. 

Would it be possible to share a VCF file that reproduces your problem also? Thanks!

**Comment by patrickturko** [comment]
Hi, Unfortunately I can't share any data as it is from patients. 

Gcc 4.9 is the default compiler. 

Before building from source I tried RTG vcfeval, and as this program works fine I have decided not pursue installing hap.py. 

Thanks for your help, you can close the issue.

**Comment by pkrusche** [comment]
Sorry to hear it didn't work for you. Let me know if you'd like to give it another try at some point! Also, hap.py can run vcfeval internally and will provide additional counting / stratification, so there may be some use for trying this at some point.

**Comment by patrickturko** [comment]
Hi, yes, I appreciate the further capabilities of hap.py, but I don't need them in this project. I don't even need ROC curves - I'm really just looking for raw matches. Maybe in the future I'll come back to hap.py.
