### ISSUE TITLE
hap.py failed when running validation process  

### ISSUE THREAD

**Issue by m891115891117** [Illumina/hap.py#29]
My script:
export HGREF=/mypath/hs37d5.fasta
hap.py /path/ctrl.vcf  /path/query.vcf -o happy.out -r /path/hs37d5.fasta
g++ version gcc/gcc-7.2.0/bin/g++
Python 2.7.13 :: Anaconda custom (64-bit)

but I still got these ERRORs :
2017-12-28 11:39:56,825 ERROR    [stderr] regex_error
2017-12-28 11:39:57,010 ERROR    Command 'quantify /tmp/hap.py.result.kQ8D10.vcf.gz -o happy.out12268.roc.tsv -r hs37d5.fasta --threads 32 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v happy.out12268.vcf.gz --roc-regions '*'' returned non-zero exit status 1
2017-12-28 11:39:57,010 ERROR    Traceback (most recent call last):
2017-12-28 11:39:57,010 ERROR      File "/nextcode/sge_software/hap/hapv0.3.10/bin/hap.py", line 511, in <module>
2017-12-28 11:39:57,021 ERROR        main()
2017-12-28 11:39:57,022 ERROR      File "/nextcode/sge_software/hap/hapv0.3.10/bin/hap.py", line 496, in main
2017-12-28 11:39:57,022 ERROR        qfy.quantify(args)
2017-12-28 11:39:57,022 ERROR      File "/nextcode/sge_software/hap/hapv0.3.10/bin/qfy.py", line 129, in quantify
2017-12-28 11:39:57,023 ERROR        strat_fixchr=args.strat_fixchr)
2017-12-28 11:39:57,023 ERROR      File "/nextcode/sge_software/hap/hapv0.3.10/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2017-12-28 11:39:57,027 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2017-12-28 11:39:57,027 ERROR      File "/nextcode/sge_software/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
2017-12-28 11:39:57,050 ERROR        raise CalledProcessError(retcode, cmd)
2017-12-28 11:39:57,051 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.kQ8D10.vcf.gz -o happy.out12268.roc.tsv -r hs37d5.fasta --threads 32 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v happy.out12268.vcf.gz --roc-regions '*'' returned non-zero exit status 1

**Comment by m891115891117** [comment]
solved this problem by reinstall hap.py using g++ version 5 or later,  you can close this issue

**Comment by pkrusche** [comment]
Thanks! I'll try it out with g++ 7 and see if it needs fixing there also.
