### ISSUE TITLE
pre.py header contig INFO issue

### ISSUE THREAD

**Issue by m891115891117** [Illumina/hap.py#36]
Hi there 

pre.py may has a small regex issue: 
the default arg --fixchr only transformed chromosome names in "main text" of a vcf file(chromosome column), while it does not transform chromosome names at the contig INFO part in header lines.    

the script pre.py used is :  
bcftools view [my.vcf.gz]  |  perl -pe 's/^([0-9XYM])/chr$1/'  |  perl -pe s/chrMT/chrM/  |  bcftools view -o /tmp/tmp.vcf.gz -O z

this works fine for main text, but it ignored header lines.  The contig info still use b37 chromosome  format(as below).  This will cause errors when I use bed file contain hg19 chr format. (like cannot creat tabix index )
eg:    
##contig=<**ID=1**,length=249250621>
##contig=<**ID=2**,length=243199373>
##contig=<**ID=3**,length=198022430>
##contig=<**ID=4,**length=191154276>
##contig=<**ID=5**,length=180915260>
##contig=<**ID=6**,length=171115067>
##contig=<ID=**7**,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG001
chr1    239339  rs184451216     A       G       50      PASS    platforms=1;platformnames=10X;datasets=1;datasetnames=10XChromium;callsets=1;c
chr1    239482  rs201702841     G       T       50      PASS    platforms=2;platformnames=10X,Illumina;datasets=2;datasetnames=10XChromium,HiS
chr1    240147  rs202156508     C       T       50      PASS    platforms=2;platformnames=10X,Illumina;datasets=2;datasetnames=10XChromium,HiS
chr1    240898  rs14799093

**Comment by pkrusche** [comment]
Thanks! Fixing this is on our backlog; it can also be fixed using a one-liner to replace `contig=<ID=... ` with `contig=<ID=chr`. 

I have not seen issues with tabix indexing; are you using tabix or bcftools to do this?

**Comment by m891115891117** [comment]
Hi Peter
when using -R option in pre.py(also -R option in bcftools), the inner build bcftools in pre.py may cause issues if the contig info not transformed. However, when using -T option, there was no error reported. 
it is because in bcftools, -R option required "sequence names must match exactly, chr20 is not the same as 20" . So, if I have a vcf file using b37 format, but the bed file is hg19 format, -R may cause the problem, and --fixchr option in pre.py will not solve this, due to the small regex issue I mentioned.  to solve this maybe just add the one-liner regex you mentioned contig=<ID=... with contig=<ID=chr behind "bcftools view [my.vcf.gz] | perl -pe 's/^([0-9XYM])/chr$1/' | perl -pe s/chrMT/chrM/" in  pre.py. 

 The options I gave and the error messages :
pre.py -r ucsc.hg19.fasta  **-R**  NA12878highconf_intersect.bed --fixchr --verbose HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2  _highconf_PGandRTGphasetransfer.vcf.gz  HG01_norm.vcf

2018-01-24 11:24:47,875 INFO     Preprocessing HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGp  hasetransfer.vcf.gz
[I] Total VCF records:         3775119
[I] Non-reference VCF records: 3775119
2018-01-24 11:25:50,286 INFO     [I] X chromosome appears to not be haploid -- assuming this is a female sample
2018-01-24 11:25:50,467 INFO     bcftools view HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGp  hasetransfer.vcf.gz  |  perl -pe 's/^([0-9XYM])/chr$1/'  |  perl -pe s/chrMT/chrM/  |  bcftools view -o /tmp/tmpdDKjMz.vcf.gz -O z
2018-01-24 11:27:39,492 INFO     bcftools index -t /tmp/tmpdDKjMz.vcf.gz
2018-01-24 11:27:58,617 INFO     bcftools view /tmp/tmpdDKjMz.vcf.gz -R intersect.bed -o /tmp/tmpT1YLtb.vcf.gz -O z
2018-01-24 11:28:08,194 INFO     bcftools index -t /tmp/tmpT1YLtb.vcf.gz
Traceback (most recent call last):
  File "hap/hapv0.3.10/bin/pre.py", line 395, in <module>
    main()
  File "hap/hapv0.3.10/bin/pre.py", line 391, in main
    preprocessWrapper(args)
  File "hap/hapv0.3.10/bin/pre.py", line 241, in preprocessWrapper
    args.somatic_allele_conversion)
  File "hap/hapv0.3.10/bin/pre.py", line 192, in preprocess
    sample=sample)
  File "hap/hapv0.3.10/lib/python27/Tools/bcftools.py", line 219, in preprocessVCF
    runBcftools("index", "-t", output)
  File "hap/hapv0.3.10/lib/python27/Tools/bcftools.py", line 49, in runBcftools
    ". Return code was %i, output: %s / %s \n" % (rc, o, e))
Exception: Error running BCFTOOLS; please check if your file has issues using vcfcheck. Return code was 255, output:  / [E::hts_idx_push] unso  rted positions on sequence #5: 114453605 followed by 114453591
index: failed to create index for "/tmp/tmpT1YLtb.vcf.gz"


 when **I change -R to -T,** its going well, there were no error messages reported. 

pre.py -r ucsc.hg19.fasta  **-T**  NA12878highconf_intersect.bed --fixchr --verbose HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2  _highconf_PGandRTGphasetransfer.vcf.gz  HG01_norm.vcf

2018-01-31 13:32:25,865 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2018-01-31 13:32:25,962 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[I] Total VCF records:         3775119
[I] Non-reference VCF records: 3775119
