### ISSUE TITLE
Exception: Cannot read sample names from truth input file

### ISSUE THREAD

**Issue by avilella** [Illumina/hap.py#4]
Downloaded `hg19/8.0.1/NA12878/NA12878.vcf.gz` and index file from the Platinum Genomes ftp site.
Running on a small `test.vcf.gz` file like so:

```
sudo docker run -it -v $PWD:/data/input -v $GROUP/PlatinumGenomes/:/data/PlatinumGenomes pkrusche/hap.py /opt/hap.py/bin/hap.py /data/PlatinumGenomes/hg19/8.0.1/NA12878/NA12878.vcf.gz /data/input/test.vcf.gz -o /data/test                     2015-12-02 10:16:54,779 WARNING  Reference sequence check failed! Please ensure that truth and query VCF use the same reference sequence as hap.py. XCMP may fail if this is not the case, and the results will not be  accurate.
2015-12-02 10:16:54,779 WARNING  No calls for location chr2 in query!
2015-12-02 10:16:54,779 WARNING  No calls for location chr3 in query!
2015-12-02 10:16:54,779 WARNING  No calls for location chr4 in query!
2015-12-02 10:16:54,779 WARNING  No calls for location chr5 in query!
2015-12-02 10:16:54,779 WARNING  No calls for location chr6 in query!
2015-12-02 10:16:54,779 WARNING  No calls for location chr7 in query!
2015-12-02 10:16:54,779 WARNING  No calls for location chr8 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr9 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr10 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr11 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr12 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr13 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr14 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr15 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr16 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr17 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr18 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr19 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr20 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr21 in query!
2015-12-02 10:16:54,780 WARNING  No calls for location chr22 in query!
2015-12-02 10:16:56,399 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:56,453 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:56,548 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:56,632 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:56,685 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:56,800 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,102 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,400 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'CS' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'Context' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'DP' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'MQ0' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'NS' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'REF' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,400 WARNING  [W::vcf_parse] INFO 'SB' is not defined in the header, assuming Type=String
2015-12-02 10:16:57,643 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,747 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,828 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,942 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,992 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:57,992 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,074 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,329 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,345 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,377 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,451 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,508 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,622 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,626 WARNING  Could not parse the header line: "##vcfProcessLog=<InputVCF=<>, InputVCFSource=<>, InputVCFVer=<1.1>, InputVCFParam=<> InputVCFgeneAnno=<>>"
2015-12-02 10:16:58,627 ERROR    Cannot read sample names from truth input file
2015-12-02 10:16:58,627 ERROR    Traceback (most recent call last):
2015-12-02 10:16:58,627 ERROR      File "/opt/hap.py/bin/hap.py", line 804, in <module>
2015-12-02 10:16:58,627 ERROR        main()
2015-12-02 10:16:58,628 ERROR      File "/opt/hap.py/bin/hap.py", line 575, in main
2015-12-02 10:16:58,628 ERROR        raise Exception("Cannot read sample names from truth input file")
2015-12-02 10:16:58,628 ERROR    Exception: Cannot read sample names from truth input file
```

**Comment by pkrusche** [comment]
That error message is misleading (will fix that in the next release). 

It seems the header of your query file has issues (did the #CHROM #POS ... line somehow get lost?)

This can be debugged using the vcfhdr2json tool in the hap.py bin directory:

```
vcfhdr2json input.vcf.gz output.json
```

The samples key should not be empty.

**Comment by pkrusche** [comment]
The offending line in your file seems to be the vcfProcessLog header.

```
cat test.vcf | grep -v '##vcfProcess' | bgzip > test2.vcf.gz
```

... should fix the error.

**Comment by avilella** [comment]
I got it to work with the small test.vcf.gz file, trying with a WGS file
now, thx:

```
2015-12-02 10:42:02,340 WARNING  No calls for location chr2 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr3 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr4 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr5 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr6 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr7 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr8 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr9 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr10 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr11 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr12 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr13 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr14 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr15 in query!
2015-12-02 10:42:02,340 WARNING  No calls for location chr16 in query!
2015-12-02 10:42:02,341 WARNING  No calls for location chr17 in query!
2015-12-02 10:42:02,341 WARNING  No calls for location chr18 in query!
2015-12-02 10:42:02,341 WARNING  No calls for location chr19 in query!
2015-12-02 10:42:02,341 WARNING  No calls for location chr20 in query!
2015-12-02 10:42:02,341 WARNING  No calls for location chr21 in query!
2015-12-02 10:42:02,341 WARNING  No calls for location chr22 in query!
Benchmarking Summary:
                 TRUTH.TOTAL  QUERY.TOTAL  METRIC.Recall  METRIC.Precision
 METRIC.Frac_NA
Locations.INDEL       587124            0       0.000010          0.000000
              0
Locations.SNP        3565408        99874       0.010327          0.368765
              0
```
