### ISSUE TITLE
qfy.py killed

### ISSUE THREAD

**Issue by teodora-aleksic** [Illumina/hap.py#43]
Hi,

I'm running qfy.py using a vcf produced by vcfeval in ga4gh mode. The execution lasts around 2h after which it fails. The command line and the stderr are the following:

```
python hap.py/bin/qfy.py --report-prefix combined --write-vcf --write-counts --verbose --type ga4gh --threads 8 --stratification stratification.tsv --roc-delta 20 --roc QQ --reference human_g1k_v37_decoy.fasta combined.vcf.gz
```

```
2018-03-12T17:39:59.736617253Z 2018-03-12 17:39:59,089 ERROR    [stderr] Added region file 'truseq.bed' as 'truseq' (214115 intervals)
2018-03-12T17:39:59.800729266Z 2018-03-12 17:39:59,666 ERROR    [stderr] Killed
2018-03-12T17:39:59.800761058Z 2018-03-12 17:39:59,728 ERROR    Command 'quantify combined.vcf.gz -o combined.roc.tsv -r human_g1k_v37_decoy.fasta --threads 8 --output-vtc 0 --output-rocs 1 --type ga4gh --qq QQ --roc-delta 20.000000 --clean-info 1 --fix-chr-regions 0 -v combined.vcf.gz -R 'truseq:truseq.bed' --roc-regions '*'' returned non-zero exit status 137
2018-03-12T17:39:59.801256247Z 2018-03-12 17:39:59,750 ERROR    Traceback (most recent call last):
2018-03-12T17:39:59.801259753Z 2018-03-12 17:39:59,761 ERROR      File "/opt/hap.py/bin/qfy.py", line 378, in <module>
2018-03-12T17:39:59.872980577Z 2018-03-12 17:39:59,865 ERROR        main()
2018-03-12T17:39:59.873145682Z 2018-03-12 17:39:59,872 ERROR      File "/opt/hap.py/bin/qfy.py", line 374, in main
2018-03-12T17:39:59.873228664Z 2018-03-12 17:39:59,873 ERROR        quantify(args)
2018-03-12T17:39:59.890464487Z 2018-03-12 17:39:59,873 ERROR      File "/opt/hap.py/bin/qfy.py", line 129, in quantify
2018-03-12T17:39:59.890505413Z 2018-03-12 17:39:59,873 ERROR        strat_fixchr=args.strat_fixchr)
2018-03-12T17:39:59.890519038Z 2018-03-12 17:39:59,874 ERROR      File "/opt/hap.py/lib/python27/Haplo/quantify.py", line 178, in run_quantify
2018-03-12T17:39:59.911044306Z 2018-03-12 17:39:59,910 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2018-03-12T17:39:59.911065951Z 2018-03-12 17:39:59,910 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2018-03-12T17:39:59.951891424Z 2018-03-12 17:39:59,951 ERROR        raise CalledProcessError(retcode, cmd)
2018-03-12T17:39:59.965796603Z 2018-03-12 17:39:59,964 ERROR    CalledProcessError: Command 'quantify combined.vcf.gz -o combined.roc.tsv -r human_g1k_v37_decoy.fasta --threads 8 --output-vtc 0 --output-rocs 1 --type ga4gh --qq QQ --roc-delta 20.000000 --clean-info 1 --fix-chr-regions 0 -v combined.vcf.gz -R 'truseq:truseq.bed' --roc-regions '*'' returned non-zero exit status 137
```

I'd be happy to share the input files if that would help.

P.S. I truncated the file paths from the stderr just for simplicity's sake.

Thanks

**Comment by pkrusche** [comment]
What is the memory available on your machine (or to the job when submitted on a queue) / Is is possible that quantify runs out of memory? Especially when using large region bed files, memory requirements can go up.

**Comment by teodora-aleksic** [comment]
It's got 16GB of RAM. I can try and run it on a larger machine. I'm looking at the memory usage during the execution and it's bellow 2GB during those 2h. It only peaks at the last 2-3 min and then fails.

**Comment by pkrusche** [comment]
If you run with `--verbose`, and `--keep-scratch` + `--scratch-prefix <DIR>` you can see if quantify produces a (possibly large) TSV file which then eats up memory when being loaded for postprocessing. One possibility is that your bed file contains a fourth column, which will produce a very large number of stratification regions. If this is not intended, speedup + memory reduction can be achieved by supplying a bed file that only contains chrom, start, end columns.

**Comment by teodora-aleksic** [comment]
It does contain a fourth column. I'll remove it and rerun with the options you suggested.

**Comment by teodora-aleksic** [comment]
Yep, it was the fourth column's fault. It finished under 2 min now. Thanks!
