### ISSUE TITLE
Counting local matches

### ISSUE THREAD

**Issue by apregier** [Illumina/hap.py#44]
I have a question related to calculating local match statistics.  The paper suggests:
TP.LM = QUERY.TP + FP.GT + FP.AL
FN.LM = TRUTH.FN - FP.GT - FP.AL
FP.LM = QUERY.FP - FP.GT - FP.AL
It seems that the FP.AL are counted relative to the query.  If I try to use those numbers relative to the truth set (for example to calculate recall with local matching) I get numbers that don't make sense, simply because the local matches aren't 1-to-1.  Perhaps this is simply a feature request, but is there a way to get the FN.AL counts?  Or am I interpreting something wrong?

**Comment by apregier** [comment]
And, this may apply to FP.GT as well, I'm not sure...what do you think?

**Comment by pkrusche** [comment]
For FP.GT, I think the FN.GT value should be the same as the FPs (at lease when using xcmp) since this only happens when two records match except for the genotype (i.e. truth and query representation will be the same). Another way to do this type of comparison would be to add `--set-gt het` to force 0/1 genotypes for all calls.

It is true that in the FP.AL case things are a bit trickier -- if the representations between truth and query are very different this could be problematic. However, ignoring FP.AL is basically distance-based comparison, hap.py should be able to do this directly using `--engine=scmp-distance --scmp-distance 50`; this will match everything that is closer than 50bp.

Hope this helps?

**Comment by apregier** [comment]
Ok, I will give that a try, thank you!

**Comment by virenar** [comment]
I am trying the `scmp-distance` engine but getting following error 

```
[I] Total VCF records:         3775119
[I] Non-reference VCF records: 3775119
[I] Total VCF records:         13317
[I] Non-reference VCF records: 361
2018-10-01 17:45:41,260 ERROR    Exception when running scmp: Error running BCFTOOLS; please check if your file has issues using vcfcheck. Return code was 255, output:  / Warning: trying to combine "GQ" tag definitions of different types
Warning: trying to combine "AD" tag definitions of different lengths
Incorrect number of AD fields (2) at chr1:21889635, cannot merge.
 

2018-10-01 17:45:41,261 ERROR    ------------------------------------------------------------
2018-10-01 17:45:41,264 ERROR    Traceback (most recent call last):
2018-10-01 17:45:41,264 ERROR      File "/opt/hap.py/lib/python27/Haplo/scmp.py", line 46, in runSCmp
2018-10-01 17:45:41,266 ERROR        runBcftools(*vargs)
2018-10-01 17:45:41,266 ERROR      File "/opt/hap.py/lib/python27/Tools/bcftools.py", line 50, in runBcftools
2018-10-01 17:45:41,267 ERROR        ". Return code was %i, output: %s / %s \n" % (rc, o, e))
2018-10-01 17:45:41,267 ERROR    Exception: Error running BCFTOOLS; please check if your file has issues using vcfcheck. Return code was 255, output:  / Warning: trying to combine "GQ" tag definitions of different typesWarning: trying to combine "AD" tag definitions of different lengthsIncorrect number of AD fields (2) at chr1:21889635, cannot merge. 
2018-10-01 17:45:41,267 ERROR    ------------------------------------------------------------
2018-10-01 17:45:41,273 ERROR    Error running BCFTOOLS; please check if your file has issues using vcfcheck. Return code was 255, output:  / Warning: trying to combine "GQ" tag definitions of different types
Warning: trying to combine "AD" tag definitions of different lengths
Incorrect number of AD fields (2) at chr1:21889635, cannot merge.
 

2018-10-01 17:45:41,273 ERROR    Traceback (most recent call last):
2018-10-01 17:45:41,273 ERROR      File "/opt/hap.py/bin/hap.py", line 511, in <module>
2018-10-01 17:45:41,274 ERROR        main()
2018-10-01 17:45:41,274 ERROR      File "/opt/hap.py/bin/hap.py", line 459, in main
2018-10-01 17:45:41,274 ERROR        tempfiles += Haplo.scmp.runSCmp(args.vcf1, args.vcf2, output_name, args)
2018-10-01 17:45:41,274 ERROR      File "/opt/hap.py/lib/python27/Haplo/scmp.py", line 46, in runSCmp
2018-10-01 17:45:41,274 ERROR        runBcftools(*vargs)
2018-10-01 17:45:41,274 ERROR      File "/opt/hap.py/lib/python27/Tools/bcftools.py", line 50, in runBcftools
2018-10-01 17:45:41,274 ERROR        ". Return code was %i, output: %s / %s \n" % (rc, o, e))
2018-10-01 17:45:41,275 ERROR    Exception: Error running BCFTOOLS; please check if your file has issues using vcfcheck. Return code was 255, output:  / Warning: trying to combine "GQ" tag definitions of different typesWarning: trying to combine "AD" tag definitions of different lengthsIncorrect number of AD fields (2) at chr1:21889635, cannot merge. 
```

I even tried removing the `AD` from VCF but the problem still persists. 

I tried merging the VCFs myself. It gave me warnings but was able to merge the files

```
root@4b74e02afe41:/# /opt/hap.py/bin/bcftools merge tmp/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.vcf.gz tmp/S1.genome.vcf.gz -O v -o m.vcf
Warning: trying to combine "AD" tag definitions of different lengths
Warning: trying to combine "GQ" tag definitions of different types
```

Can someone please point me the right direction?
