### ISSUE TITLE
Haploid genome benchmarking

### ISSUE THREAD

**Issue by ksw9** [Illumina/hap.py#47]
Thanks for a great tool - can I also use this for benchmarking haploid genomes?
Thank you,

**Comment by pkrusche** [comment]
It depends on how the variants are represented in VCF. If they are output as `GT 1` then they may need to be converted into `GT 1/1`. Hap.py has a command line switch to do this: `--set-gt hom`. This will turn all genotypes into `1/1`, which (unless there are multiallelics) forces haploid comparison. Another relevant option would be to add a feature to hap.py which can use `--squash-ploidy` in vcfeval, though the behaviour for this is slightly different (see https://github.com/Illumina/hap.py/issues/42).

**Comment by ksw9** [comment]
Thank you! This is great. One more question - I am using a truth vcf that I have created from a multiple alignment of samples (i.e. it contains sites of variant positions but no sample information). I am running into the error: 
Input file has no samples. Hap.py will not like that.

I am wondering how the truth VCF file needs to be formatted? Does it need to contain genotypes?

Thank you!

**Comment by ksw9** [comment]
For example, the first few lines of my VCF:

```
##fileformat=VCFv4.1
##contig=<ID=NC_000962.3,length=4411532,assembly=H37Rv>
##reference=xxx
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
NC_000962.3	1977	.	A	G	.	.	.
NC_000962.3	4013	.	T	C	.	.	.
NC_000962.3	7362	.	G	C	.	.	.
NC_000962.3	7585	.	G	C	.	.	.
```

I also tried updating this to: 
```
##fileformat=VCFv4.1
##contig=<ID=NC_000962.3,length=4411532,assembly=H37Rv>
##reference=xxx
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	FORMAT	TRUTH
NC_000962.3 1977 . A G . . GT   1/1
NC_000962.3 4013 . T C . . GT   1/1
NC_000962.3 7362 . G C . . GT   1/1
NC_000962.3 7585 . G C . . GT   1/1

``` 

But I ran into the same error. Any suggestions would be great, thank you!

**Comment by pkrusche** [comment]
I think you're missing the INFO column. Also, it might be necessary to add a header entry for the GT FORMAT field.

**Comment by ksw9** [comment]
Great, thank you, this worked.
I am running into errors with hap.py though and I'm not sure what the error messages means:

hap.py -r $REF_DIR'H37Rv.fa' test.vcf.gz $query'.gz' -o test --write-counts --roc QUAL --threads 7 

[GCA_000008585.1_10_1.bwa_deep_trained.vcf.gz](https://github.com/Illumina/hap.py/files/1952300/GCA_000008585.1_10_1.bwa_deep_trained.vcf.gz)

[test.vcf.gz](https://github.com/Illumina/hap.py/files/1952301/test.vcf.gz)

`
2018-04-26 10:29:29,792 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2018-04-26 10:29:29,812 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[I] Total VCF records:         1
[I] Non-reference VCF records: 1
[I] Total VCF records:         2500
[I] Non-reference VCF records: 1513
2018-04-26 10:29:31,867 ERROR    [stderr] regex_error
2018-04-26 10:29:31,868 ERROR    Command 'quantify /tmp/hap.py.result.M6aWlz.vcf.gz -o test.roc.tsv -r /ifs/labs/andrews/walter/varcal/data/refs/H37Rv.fa --threads 7 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test.vcf.gz --roc-regions '*'' returned non-zero exit status 1
2018-04-26 10:29:31,868 ERROR    Traceback (most recent call last):
2018-04-26 10:29:31,869 ERROR      File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/hap.py_0.3.7/bin/hap.py", line 460, in <module>
2018-04-26 10:29:31,870 ERROR        main()
2018-04-26 10:29:31,871 ERROR      File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/hap.py_0.3.7/bin/hap.py", line 445, in main
2018-04-26 10:29:31,871 ERROR        qfy.quantify(args)
2018-04-26 10:29:31,871 ERROR      File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/hap.py_0.3.7/bin/qfy.py", line 129, in quantify
2018-04-26 10:29:31,872 ERROR        strat_fixchr=args.strat_fixchr)
2018-04-26 10:29:31,873 ERROR      File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/hap.py_0.3.7/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2018-04-26 10:29:31,874 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2018-04-26 10:29:31,874 ERROR      File "/scg/apps/software/anaconda/3_5.0.1_20180125/envs/hap.py_0.3.7/lib/python2.7/subprocess.py", line 186, in check_call
2018-04-26 10:29:31,876 ERROR        raise CalledProcessError(retcode, cmd)
2018-04-26 10:29:31,877 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.M6aWlz.vcf.gz -o test.roc.tsv -r /ifs/labs/andrews/walter/varcal/data/refs/H37Rv.fa --threads 7 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test.vcf.gz --roc-regions '*'' returned non-zero exit status 1`

I am attaching my sample truth vcf (test.vcf.gz which includes only a single variant for testing) and my VCF file, GCA_000008585.1_10_1.bwa_deep_trained.vcf.gz. Does this error signify something specific? Thank you!

**Comment by pkrusche** [comment]
The warnings aren't the thing that goes wrong, but there is a problematic error message hidden in there: `ERROR [stderr] regex_error`.

This error will occur when hap.py was compiled with a version of g++ that is too old (the minimum recommended version is 4.9.2) -- could you share some information on compiler / operating system versions?
