### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by ManavalanG** [Illumina/hap.py#52]
hap.py fails for vcfs due to presence of star ALT alleles, and I am still trying to figure out how to best deal with this. In the process, I found a bug in error reporting, where variant positions appear to be using zero-indexing instead of one-indexing. For example, in the error log snippet below, ` 1:15273` should actually be ` 1:15274`. I'm using hap.py v0.3.10.

    2018-05-15 14:58:27,833 ERROR    Preprocess command preprocess /tmp/tmpkHm0Sh.vcf.gz:* -o /tmp/input.akWCP_.prep.vcf.gz -V 1 -L 0 -r ref_genome/grch37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdout3Yq7WQ.log / /tmp/stderrimbr59.log
    2018-05-15 14:58:27,834 ERROR    [W] too many AD fields at 1:15273 max_ad = 2 retrieved: 3
    2018-05-15 14:58:27,834 ERROR    [W] too many AD fields at 1:20226 max_ad = 2 retrieved: 3
    2018-05-15 14:58:27,836 ERROR    [W] too many AD fields at 1:54711 max_ad = 2 retrieved: 4
    2018-05-15 14:58:27,836 ERROR    [W] too many AD fields at 1:54723 max_ad = 2 retrieved: 3
    2018-05-15 14:58:27,836 ERROR    [W] too many AD fields at 1:82132 max_ad = 2 retrieved: 4
    2018-05-15 14:58:27,841 ERROR    Exception when running <function preprocessWrapper at 0x2aaad1e11cf8>:
    2018-05-15 14:58:27,841 ERROR    ------------------------------------------------------------
    2018-05-15 14:58:27,841 ERROR    Traceback (most recent call last):
    2018-05-15 14:58:27,842 ERROR      File "/dddd/software/happy-0.3.10/lib/python27/Tools/parallel.py", line 72, in parMapper
    2018-05-15 14:58:27,851 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
    2018-05-15 14:58:27,851 ERROR      File "/dddd/software/happy-0.3.10/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
    2018-05-15 14:58:27,884 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
    2018-05-15 14:58:27,884 ERROR      File "/gpfs/gpfs1/software/Python-2.7.11/lib/python2.7/subprocess.py", line 540, in check_call
    2018-05-15 14:58:27,897 ERROR        raise CalledProcessError(retcode, cmd)
    2018-05-15 14:58:27,897 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpkHm0Sh.vcf.gz:* -o /tmp/input.akWCP_.prep.vcf.gz -V 1 -L 0 -r ref_genome/grch37/human_g1k_v37.fasta' returned non-zero exit status -6
    2018-05-15 14:58:27,898 ERROR    ------------------------------------------------------------
    2018-05-15 14:58:27,909 ERROR    One of the preprocess jobs failed
    2018-05-15 14:58:27,909 ERROR    Traceback (most recent call last):
    2018-05-15 14:58:27,909 ERROR      File "/dddd/software/happy-0.3.10/bin/hap.py", line 511, in <module>
    2018-05-15 14:58:27,917 ERROR        main()
    2018-05-15 14:58:27,917 ERROR      File "/dddd/software/happy-0.3.10/bin/hap.py", line 366, in main
    2018-05-15 14:58:27,918 ERROR        "QUERY")
    2018-05-15 14:58:27,918 ERROR      File "/dddd/software/happy-0.3.10/bin/pre.py", line 203, in preprocess
    2018-05-15 14:58:27,925 ERROR        haploid_x=gender == "male")
    2018-05-15 14:58:27,926 ERROR      File "/dddd/software/happy-0.3.10/lib/python27/Haplo/partialcredit.py", line 214, in partialCredit
    2018-05-15 14:58:27,926 ERROR        raise Exception("One of the preprocess jobs failed")
    2018-05-15 14:58:27,926 ERROR    Exception: One of the preprocess jobs failed

**Comment by pkrusche** [comment]
I think one workaround might be to remove the AD field from the input VCF with bcftools annotate. It is not used by hap.py, and I think the * alleles should be ok once all FORMAT fields which have a problematic number of elements are removed.

**Comment by ManavalanG** [comment]
@pkrusche Thanks for the suggestion. I prefer to retain AD fields for post analysis. May be I should try removing them and figure out other ways to extract/match AD info.
