### ISSUE TITLE
ERROR    [stderr] regex_error

### ISSUE THREAD

**Issue by Xingsl** [Illumina/hap.py#66]
Dear,
when i run this 
    hap.py  Standard.wes.vcf  Standard.wes.vcf -o NA12878 --threads 6 
it produced 

2018-11-03 14:53:14,187 ERROR    [stderr] regex_error
2018-11-03 14:53:14,199 ERROR    Command 'quantify /tmp/hap.py.result.P5wuqJ.vcf.gz -o NA12878.roc.tsv -r /data/Reference/fasta/hs.grch38.fa --threads 6 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v NA12878.vcf.gz --roc-regions '*'' returned non-zero exit status 1
2018-11-03 14:53:14,200 ERROR    Traceback (most recent call last):
2018-11-03 14:53:14,200 ERROR      File "/bin/hap.py", line 511, in <module>
2018-11-03 14:53:14,201 ERROR        main()
2018-11-03 14:53:14,201 ERROR      File "/bin/hap.py", line 496, in main
2018-11-03 14:53:14,201 ERROR        qfy.quantify(args)
2018-11-03 14:53:14,201 ERROR      File "/bin/qfy.py", line 129, in quantify
2018-11-03 14:53:14,202 ERROR        strat_fixchr=args.strat_fixchr)
2018-11-03 14:53:14,202 ERROR      File "/bin/lib/python27/Haplo/quantify.py", line 178, in run_quantify
2018-11-03 14:53:14,202 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2018-11-03 14:53:14,202 ERROR      File "/anaconda2/envs/python27/lib/python2.7/subprocess.py", line 190, in check_call
2018-11-03 14:53:14,204 ERROR        raise CalledProcessError(retcode, cmd)
2018-11-03 14:53:14,204 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.P5wuqJ.vcf.gz -o NA12878.roc.tsv -r /data/Reference/fasta/hs.grch38.fa --threads 6 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v NA12878.vcf.gz --roc-regions '*'' returned non-zero exit status 1

**Comment by pkrusche** [comment]
Which version of g++ are you using to compile hap.py? Older versions than 4.9.2 can cause issues with their implementation of std::regex.

**Comment by nh13** [comment]
I hit this same error installed using [bioconda](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hap.py/meta.yaml).  g++ is version 4.8.5.  The [hap.py README](https://github.com/Illumina/hap.py#compiling-from-source-with-cmake) states:
> GCC/G++ 4.8+ for compiling

**Comment by afkoeppel** [comment]
I'm getting this exact same error, but with gcc 7.2.0.

conda create -n happy python=2.7 numpy scipy pandas pysam bx-python hap.py cmake
conda activate happy
gcc --version
gcc (crosstool-NG fa8859cb) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.

hap.py NA12878.chrfix.vcf.gz NA12878.filt.decomp.norm.annot.ready.vcf.gz -o test -r $HG19 --no-leftshift --no-decompose --gender=none
[I] Total VCF records:         4049512
[I] Non-reference VCF records: 4049512
[W] overlapping records at 1:7164311 for sample 0
[W] Variants that overlap on the reference allele: 6
[I] Total VCF records:         4602744
[I] Non-reference VCF records: 4525967
2018-12-18 09:48:52,094 ERROR    [stderr] regex_error
2018-12-18 09:48:52,393 ERROR    Command 'quantify /tmp/hap.py.result.dGcyjP.vcf.gz -o fulltest.roc.tsv -r /home/afk2s/data/fastq2vcf/ASSETS/human_g1k_v37.fasta --threads 72 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v fulltest.vcf.gz --roc-regions '*'' returned non-zero exit status 1
2018-12-18 09:48:52,396 ERROR    Traceback (most recent call last):
2018-12-18 09:48:52,397 ERROR      File "/home/afk2s/Software/miniconda3/envs/happy/bin/hap.py", line 511, in <module>
2018-12-18 09:48:52,398 ERROR        main()
2018-12-18 09:48:52,398 ERROR      File "/home/afk2s/Software/miniconda3/envs/happy/bin/hap.py", line 496, in main
2018-12-18 09:48:52,398 ERROR        qfy.quantify(args)
2018-12-18 09:48:52,398 ERROR      File "/home/afk2s/Software/miniconda3/envs/happy/bin/qfy.py", line 129, in quantify
2018-12-18 09:48:52,399 ERROR        strat_fixchr=args.strat_fixchr)
2018-12-18 09:48:52,399 ERROR      File "/home/afk2s/Software/miniconda3/envs/happy/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2018-12-18 09:48:52,400 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2018-12-18 09:48:52,400 ERROR      File "/home/afk2s/Software/miniconda3/envs/happy/lib/python2.7/subprocess.py", line 190, in check_call
2018-12-18 09:48:52,401 ERROR        raise CalledProcessError(retcode, cmd)
2018-12-18 09:48:52,401 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.dGcyjP.vcf.gz -o fulltest.roc.tsv -r /home/afk2s/data/fastq2vcf/ASSETS/human_g1k_v37.fasta --threads 72 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v fulltest.vcf.gz --roc-regions '*'' returned non-zero exit status 1

Any help or advice would be appreciated.  Thanks.

**Comment by nh13** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/12581

It’s not working in bioconda either.

**Comment by stephenturner** [comment]
I'm running into the same problem. My gcc is 4.8.5. Not working via bioconda either.

**Comment by wdecoster** [comment]
I have the same problem, installed using bioconda, using gcc 7.3.0. If there is anything I can test to debug this, please let me know.

**Comment by pkrusche** [comment]
@nh13 @stephenturner @wdecoster hap.py has issues with gcc < 4.9.x (regex errors) and apparently also with 7.3 (unit test failure). From what I can tell, Bioconda has been in the process of switching from 4.8 to 7.3, so there will be issues with both. 

Here is a branch that should fix these issues: 

https://github.com/pkrusche/hap.py/tree/fix-with-gcc-7-3

**Comment by stephenturner** [comment]
Awesome. I will try this out soon. cc @punkrockscience, give it a try?

**Comment by wdecoster** [comment]
I tried, but if I'm not installing using conda it fails building, and I cannot figure out what's wrong. I've attached the output log to this message.
The error refers to a `/tmp/buildL4RUN_/CMakeFiles/CMakeOutput.log` which doesn't seem to exist.
I tried installing using `python2.7 install.py ~/hap.py-install` (my default python interpreter is python3).


[building-log.txt](https://github.com/Illumina/hap.py/files/3140780/building-log.txt)

**Comment by pkrusche** [comment]
Seems you’re missing libbz2-dev for building boost.

You could supply your own Boost build (the readme has instructions) or install libbz2-dev.

**Comment by HuTaoJiaZiAckerman** [comment]
When I use gcc or g++ 11.2 from conda, but it not work. 

Because I can't install right g++ version, **I use hap.py from docker.** It seemly get result.

Good luck!
