### ISSUE TITLE
command quantify while running the below command 

### ISSUE THREAD

**Issue by KrithikaSubramanian** [Illumina/hap.py#75]
If I run this command
hap.py-build/bin/hap.py Platinum_genome/split/chr1.recode.vcf 11_Haplotypecaller_indelrealigner/SRR622457_chr1.vcf -f 11_gatk_targetrealign/Chr1_SRR622457.bed -r /root/Work/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa --scratch-prefix Temp/ -o test

2019-02-11 14:08:50,974 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-02-11 14:08:50,975 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[I] Total VCF records:         316061
[I] Non-reference VCF records: 316061
[W] overlapping records at chr1:21916069 for sample 0
[W] Variants that overlap on the reference allele: 43
[I] Total VCF records:         293051
[I] Non-reference VCF records: 292995
2019-02-11 14:09:37,806 ERROR    [stderr] regex_error
2019-02-11 14:09:37,819 ERROR    Command 'quantify /root/Work/gatk4_work/NA12878_qc/Temp/hap.py.result._j_1zJ.vcf.gz -o test.roc.tsv -r /root/Work/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa --threads 48 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test.vcf.gz -R 'CONF_VARS:/root/Work/gatk4_work/NA12878_qc/Temp/tmpnwtGCs.bed' -R 'CONF:11_gatk_targetrealign/Chr1_SRR622457.bed' --roc-regions '*'' returned non-zero exit status 1
2019-02-11 14:09:37,819 ERROR    Traceback (most recent call last):
2019-02-11 14:09:37,819 ERROR      File "hap.py-build/bin/hap.py", line 511, in <module>
2019-02-11 14:09:37,820 ERROR        main()
2019-02-11 14:09:37,820 ERROR      File "hap.py-build/bin/hap.py", line 496, in main
2019-02-11 14:09:37,820 ERROR        qfy.quantify(args)
2019-02-11 14:09:37,820 ERROR      File "/root/Work/gatk4_work/NA12878_qc/hap.py-build/bin/qfy.py", line 129, in quantify
2019-02-11 14:09:37,821 ERROR        strat_fixchr=args.strat_fixchr)
2019-02-11 14:09:37,821 ERROR      File "/root/Work/gatk4_work/NA12878_qc/hap.py-build/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2019-02-11 14:09:37,821 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2019-02-11 14:09:37,821 ERROR      File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
2019-02-11 14:09:37,822 ERROR        raise CalledProcessError(retcode, cmd)
2019-02-11 14:09:37,822 ERROR    CalledProcessError: Command 'quantify /root/Work/gatk4_work/NA12878_qc/Temp/hap.py.result._j_1zJ.vcf.gz -o test.roc.tsv -r /root/Work/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa --threads 48 --output-vtc 0 --output-rocs 1 --type xcmp --qq IQQ --qq-header QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v test.vcf.gz -R 'CONF_VARS:/root/Work/gatk4_work/NA12878_qc/Temp/tmpnwtGCs.bed' -R 'CONF:11_gatk_targetrealign/Chr1_SRR622457.bed' --roc-regions '*'' returned non-zero exit status 1

Please help me to fix this issues

Krithika S

**Comment by pkrusche** [comment]
This is probably caused by an outdated version of g++ being used (< 4.9.x), see also https://github.com/Illumina/hap.py/issues/13#issuecomment-286348476

**Comment by pkrusche** [comment]
(the key thing is the `regex_error` in the output -- this happens with older versions of g++)

**Comment by KrithikaSubramanian** [comment]
@pkrusche 

I have installed 4.9.2 version of g++. The below is the version detail

g++ --version
g++ (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by KrithikaSubramanian** [comment]
Thanks its working
