### ISSUE TITLE
hap.py annotated VCF file as output issues running with docker 

### ISSUE THREAD

**Issue by achimmiri** [Illumina/hap.py#81]
I am not running multisample VCF file 

anusha@Precision-7920-Tower:~/TESTBEN1$ sudo docker run -it -v `pwd`:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/NA12878.vcf.gz /data/PRO001B.vcf.gz -r /data/genome.fa -f /data/ConfidentRegions.bed.gz -V -o PRO001B_happy --no-leftshift --no-decompose --gender=none --engine=vcfeval
[sudo] password for anusha: 
2019-04-24 08:48:01,232 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-04-24 08:48:01,244 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[I] Total VCF records:         4167900
[I] Non-reference VCF records: 4167900
[W] variant at chr1:1035169 has more than one base of reference padding 
[W] overlapping records at chr1:55075667 for sample 1
[W] Variants that have >1 base of reference padding: 2990
[W] Variants that overlap on the reference allele: 24
[I] Total VCF records:         4208286
[I] Non-reference VCF records: 4207104
2019-04-24 08:50:36,855 WARNING  Creating template for vcfeval. You can speed this up by supplying a SDF template that corresponds to /data/genome.fa
2019-04-24 08:51:59,372 ERROR    Error running rtg tools / vcfeval. Return code was 1, output:  / Error: No sample name provided but calls is a multi-sample VCF.
 

2019-04-24 08:51:59,373 ERROR    Traceback (most recent call last):
2019-04-24 08:51:59,373 ERROR      File "/opt/hap.py/bin/hap.py", line 508, in <module>
2019-04-24 08:51:59,373 ERROR        main()
2019-04-24 08:51:59,373 ERROR      File "/opt/hap.py/bin/hap.py", line 452, in main
2019-04-24 08:51:59,373 ERROR        tempfiles += Haplo.vcfeval.runVCFEval(args.vcf1, args.vcf2, output_name, args)
2019-04-24 08:51:59,373 ERROR      File "/opt/hap.py/lib/python27/Haplo/vcfeval.py", line 129, in runVCFEval
2019-04-24 08:51:59,373 ERROR        raise Exception("Error running rtg tools / vcfeval. Return code was %i, output: %s / %s \n" % (rc, o, e))
2019-04-24 08:51:59,373 ERROR    Exception: Error running rtg tools / vcfeval. Return code was 1, output:  / Error: No sample name provided but calls is a multi-sample VCF.

**Comment by pkrusche** [comment]
Can you paste the column header line of that VCF file? Maybe there is a spurious tab / space at the end of th e `#CHROM ...` line?
