### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by ktadler** [Illumina/hap.py#83]
Hi
i've tried to run the docker:

 but keep get the "no reference" error after downloading the reference and following all of instructions on downloading (with Peter's script) the fasta, which looks totally OK to me :

(base) katie@katie-huts:~/hap.py$ less hg19.fa | head -n 1000000 | tail -n 10
CTCATATTCTTGTCTGCTGGGTTTCTGATCCTGCTTCACCTTGACCTTGG
ATTTGAACATATTCTTAGACACCTGATCTTTGGCTTGGCTTTTAACTACC
TAGCCCCAACACTAGCCCTGCAAGTGTGAGTCACGCTGCAGGTTGGGCAT
AGATTTGGGAATGAGTTGAAGCACAGAATCTGCAGATTTGGGGATTTCGC
CAAAGAGAAGGGTCTAGGGTTTCTAAAGAGGGGTCAAATTTCTATAATAC
TCTATCAACTTTCTAAGTATAACCACCAATTGaataaacatttcttggac
atcaactaaaaagcatttttctattcccttgcatgtgttagctcattaaa
tcctcacaaaagccccatgaagcagggatcaacaccattttacaaaaaaa
aaaaaaaaaaaaaaaaagcacaaaaattacctatgggcacaGAATACAAG
TCAAAATGCATGCCACAATATGGCTAAAATAATGATGTTCTTTAAATAGA

(base) katie@katie-huts:~/hap.py$ export HG19="hg19.fa"
(base) katie@katie-huts:~/hap.py$ export HGREF="hg19.fa"

(base) katie@katie-huts:~/hap.py$ sudo docker run -it -v `pwd`:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/example/PG_performance.vcf.gz /data/example/performance.vcf.gz -r hg19.fa -o /data/test 

2019-05-20 10:52:12,773 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-05-20 10:52:12,825 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-05-20 10:52:13,825 ERROR    Please specify a valid reference path using -r.
2019-05-20 10:52:13,825 ERROR    Traceback (most recent call last):
2019-05-20 10:52:13,825 ERROR      File "/opt/hap.py/bin/hap.py", line 508, in <module>
2019-05-20 10:52:13,896 ERROR        main()
2019-05-20 10:52:13,896 ERROR      File "/opt/hap.py/bin/hap.py", line 208, in main
2019-05-20 10:52:13,896 ERROR        raise Exception("Please specify a valid reference path using -r.")
2019-05-20 10:52:13,896 ERROR    Exception: Please specify a valid reference path using -r.

what am i doing wrong?
thanks

**Comment by pkrusche** [comment]
I think two things are happening: 

* hg19.fa is present in `pwd`, which gets mounted as /data; so the `-r` switch should be `-r /data/hg19.fa`

* To pass the environment variable into Docker, I think the command line would be `docker run -e HGREF=/data/hg19.fa ...`.

**Comment by ktadler** [comment]
you are totally right! fixed it, thank you so much!
