### ISSUE TITLE
Post installation validation test fails

### ISSUE THREAD

**Issue by Adigorla** [Illumina/hap.py#95]
I installed the latest hap.py successfully. But the built-in post-installation testing fails during Faulty variant test. Here's the error output:

Test for reading and detecting problematic records: Hap.py v0.3.10-8-gdac84d9 from /u/home/a/adityago/hap.py-install/bin
[W] Unsupported REF allele with undefined length: A.
[W] Unsupported REF allele with undefined length: .A
[W] Alleles with uncertain length at chrQ:3
[W] Variants that have alleles with uncertain length: 2
[I] Total VCF records:         4
[I] Non-reference VCF records: 3
[W] Unsupported REF allele with undefined length: A.
[I] Total VCF records:         1
[I] Non-reference VCF records: 1
2019-09-09 14:25:02,107 WARNING  [W] Unsupported REF allele with undefined length: A.
2019-09-09 14:25:02,108 WARNING  Blocksplit returned no blocks. This can happen when an input contains no valid variants.
2019-09-09 14:25:02,176 WARNING  [W] Unsupported REF allele with undefined length at chrQ:1-1 REF allele: A.
2019-09-09 14:25:02,294 WARNING  [W] Unsupported REF allele with undefined length: A.
2019-09-09 14:25:02,294 WARNING  [W] Unsupported REF allele with undefined length: .A
2019-09-09 14:25:02,355 WARNING  [W] Unsupported REF allele with undefined length at chrQ:1-1 REF allele: A.
2019-09-09 14:25:02,356 WARNING  [W] Unsupported REF allele with undefined length at chrQ:2-2 REF allele: .A
2019-09-09 14:25:02,461 ERROR    Cannot convert non-finite values (NA or inf) to integer
2019-09-09 14:25:02,461 ERROR    Traceback (most recent call last):
2019-09-09 14:25:02,461 ERROR      File "/u/home/a/adityago/hap.py-install/bin/hap.py", line 511, in <module>
2019-09-09 14:25:02,462 ERROR        main()
2019-09-09 14:25:02,462 ERROR      File "/u/home/a/adityago/hap.py-install/bin/hap.py", line 496, in main
2019-09-09 14:25:02,462 ERROR        qfy.quantify(args)
2019-09-09 14:25:02,462 ERROR      File "/u/home/a/adityago/hap.py-install/bin/qfy.py", line 154, in quantify
2019-09-09 14:25:02,463 ERROR        total_region_size=total_region_size)
2019-09-09 14:25:02,463 ERROR      File "/u/home/a/adityago/hap.py-install/lib/python27/Haplo/happyroc.py", line 168, in roc
2019-09-09 14:25:02,463 ERROR        result["all"][c] = result["all"][c].astype(RESULT_ALLDTYPES[i], raise_on_error=False)
2019-09-09 14:25:02,463 ERROR      File "/u/local/apps/python/2.7.16-shared/lib/python2.7/site-packages/pandas/core/generic.py", line 5691, in astype
2019-09-09 14:25:02,466 ERROR        **kwargs)
2019-09-09 14:25:02,466 ERROR      File "/u/local/apps/python/2.7.16-shared/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 531, in astype
2019-09-09 14:25:02,466 ERROR        return self.apply('astype', dtype=dtype, **kwargs)
2019-09-09 14:25:02,467 ERROR      File "/u/local/apps/python/2.7.16-shared/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 395, in apply
2019-09-09 14:25:02,467 ERROR        applied = getattr(b, f)(**kwargs)
2019-09-09 14:25:02,467 ERROR      File "/u/local/apps/python/2.7.16-shared/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 534, in astype
2019-09-09 14:25:02,468 ERROR        **kwargs)
2019-09-09 14:25:02,468 ERROR      File "/u/local/apps/python/2.7.16-shared/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 633, in _astype
2019-09-09 14:25:02,468 ERROR        values = astype_nansafe(values.ravel(), dtype, copy=True)
2019-09-09 14:25:02,468 ERROR      File "/u/local/apps/python/2.7.16-shared/lib/python2.7/site-packages/pandas/core/dtypes/cast.py", line 676, in astype_nansafe
2019-09-09 14:25:02,468 ERROR        raise ValueError('Cannot convert non-finite values (NA or inf) to '
2019-09-09 14:25:02,468 ERROR    ValueError: Cannot convert non-finite values (NA or inf) to integer
hap.py failed!
Faulty variant test FAILED!
Traceback (most recent call last):
  File "install.py", line 298, in <module>
    main()
  File "install.py", line 294, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 170, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/u/local/apps/python/2.7.16-shared/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /u/home/a/adityago/hap.py-install && /u/nobackup/eeskin2/adityago/apps/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1

Does this mean the installation was faulty or can i just ignore this? What can i do correct this?

**Comment by tirohia** [comment]
I'm also having this error, attempting to install on a linux box:

Linux version 4.19.0-041900-generic (kernel@tangerine) (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1))

**Comment by philge** [comment]
Any solution?

**Comment by genespectrum** [comment]
the same issue I am also facing. Should I just ignore the error and proceed?

**Comment by joshfactorial** [comment]
Also having this error.

**Comment by Sue9104** [comment]
I tried the docker version and found no error.

**Comment by Li3w** [comment]
Hi, ran into the same issue as above. Any solution for it?
