### ISSUE TITLE
ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.

### ISSUE THREAD

**Issue by serge2016** [Illumina/hap.py#98]
I can't get rid of this:
```
root@86876e01e030:/outputs# /opt/hap.py/bin/hap.py --threads $(nproc) --gender auto --reference /outputs/ref/human_g1k_v37/human_g1k_v37.fasta --false-positives /outputs/precFDA/challenge4-fullset.bed --report-prefix /outputs/test012_07_NovoalignGATKHC_1_src /outputs/precFDA/challenge4-fullset.vcf.gz /outputs/precFDA/challenge_results/NovoalignGATKHC_1.vcf.gz
2019-09-10 15:26:22,969 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-09-10 15:26:22,971 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[I] Total VCF records:         3775169
[I] Non-reference VCF records: 3775169
[W] overlapping records at 1:174769081 for sample 1
[W] Variants that overlap on the reference allele: 5
[I] Total VCF records:         3806019
[I] Non-reference VCF records: 3806019
2019-09-10 15:29:26,126 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:108967048-113135716 -o /tmp/input.11:108967048-113135716vF5dc8.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdout9S5jwA.log / /tmp/stderrbk5UHs.log
2019-09-10 15:29:26,127 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:26,128 ERROR    Aborted (core dumped)
2019-09-10 15:29:26,128 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:26,128 ERROR    ------------------------------------------------------------
2019-09-10 15:29:26,129 ERROR    Traceback (most recent call last):
2019-09-10 15:29:26,129 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:26,130 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:26,130 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:26,131 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:26,131 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:26,132 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:26,132 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:108967048-113135716 -o /tmp/input.11:108967048-113135716vF5dc8.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:26,133 ERROR    ------------------------------------------------------------
2019-09-10 15:29:27,655 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:1-3276637 -o /tmp/input.11:1-3276637rsaKGx.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutsQED2h.log / /tmp/stderrQsZnXG.log
2019-09-10 15:29:27,656 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:27,657 ERROR    Aborted (core dumped)
2019-09-10 15:29:27,658 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:27,658 ERROR    ------------------------------------------------------------
2019-09-10 15:29:27,659 ERROR    Traceback (most recent call last):
2019-09-10 15:29:27,659 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:27,660 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:27,661 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:27,661 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:27,662 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:27,663 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:27,663 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:1-3276637 -o /tmp/input.11:1-3276637rsaKGx.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:27,664 ERROR    ------------------------------------------------------------
2019-09-10 15:29:28,683 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:58779876-63175827 -o /tmp/input.11:58779876-63175827BdYbzZ.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutRAtLlb.log / /tmp/stderre8hq0m.log
2019-09-10 15:29:28,684 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:28,684 ERROR    Aborted (core dumped)
2019-09-10 15:29:28,684 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:28,684 ERROR    ------------------------------------------------------------
2019-09-10 15:29:28,684 ERROR    Traceback (most recent call last):
2019-09-10 15:29:28,684 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:28,684 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:28,685 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:28,685 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:28,685 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:28,686 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:28,686 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:58779876-63175827 -o /tmp/input.11:58779876-63175827BdYbzZ.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:28,686 ERROR    ------------------------------------------------------------
2019-09-10 15:29:35,427 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:82545964-86758629 -o /tmp/input.11:82545964-86758629ZxuNke.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutU0SVZQ.log / /tmp/stderrM5Kkhn.log
2019-09-10 15:29:35,427 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:35,428 ERROR    Aborted (core dumped)
2019-09-10 15:29:35,428 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:35,428 ERROR    ------------------------------------------------------------
2019-09-10 15:29:35,428 ERROR    Traceback (most recent call last):
2019-09-10 15:29:35,428 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:35,428 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:35,428 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:35,428 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:35,428 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:35,428 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:35,428 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 11:82545964-86758629 -o /tmp/input.11:82545964-86758629ZxuNke.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:35,428 ERROR    ------------------------------------------------------------
2019-09-10 15:29:39,639 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 14:33500303-35755642 -o /tmp/input.14:33500303-35755642EoFLxK.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutvORDME.log / /tmp/stderrx6ZThu.log
2019-09-10 15:29:39,639 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:39,639 ERROR    Aborted (core dumped)
2019-09-10 15:29:39,639 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:39,640 ERROR    ------------------------------------------------------------
2019-09-10 15:29:39,640 ERROR    Traceback (most recent call last):
2019-09-10 15:29:39,640 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:39,640 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:39,640 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:39,640 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:39,641 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:39,642 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:39,642 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 14:33500303-35755642 -o /tmp/input.14:33500303-35755642EoFLxK.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:39,642 ERROR    ------------------------------------------------------------
2019-09-10 15:29:41,921 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 10:72802430-78655067 -o /tmp/input.10:72802430-7865506718FRzq.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdout6Re9HN.log / /tmp/stderrKm1Csb.log
2019-09-10 15:29:41,922 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:41,922 ERROR    Aborted (core dumped)
2019-09-10 15:29:41,922 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:41,922 ERROR    ------------------------------------------------------------
2019-09-10 15:29:41,922 ERROR    Traceback (most recent call last):
2019-09-10 15:29:41,922 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:41,922 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:41,922 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:41,922 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:41,922 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:41,923 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:41,923 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 10:72802430-78655067 -o /tmp/input.10:72802430-7865506718FRzq.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:41,923 ERROR    ------------------------------------------------------------
2019-09-10 15:29:45,156 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 16:1-2098417 -o /tmp/input.16:1-2098417hbEOn2.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutbWYari.log / /tmp/stderrRuh18k.log
2019-09-10 15:29:45,160 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:45,160 ERROR    Aborted (core dumped)
2019-09-10 15:29:45,161 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:45,161 ERROR    ------------------------------------------------------------
2019-09-10 15:29:45,161 ERROR    Traceback (most recent call last):
2019-09-10 15:29:45,161 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:45,162 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:45,162 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:45,162 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:45,162 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:45,162 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:45,163 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 16:1-2098417 -o /tmp/input.16:1-2098417hbEOn2.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:45,163 ERROR    ------------------------------------------------------------
2019-09-10 15:29:46,915 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 17:66090351-67974619 -o /tmp/input.17:66090351-67974619teIX1z.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutZn5fVY.log / /tmp/stderrTCGTvy.log
2019-09-10 15:29:46,916 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:29:46,916 ERROR    Aborted (core dumped)
2019-09-10 15:29:46,916 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:29:46,917 ERROR    ------------------------------------------------------------
2019-09-10 15:29:46,917 ERROR    Traceback (most recent call last):
2019-09-10 15:29:46,917 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:29:46,917 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:29:46,917 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:29:46,918 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:29:46,918 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:29:46,918 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:29:46,919 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 17:66090351-67974619 -o /tmp/input.17:66090351-67974619teIX1z.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:29:46,919 ERROR    ------------------------------------------------------------
2019-09-10 15:30:01,823 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:130994975-135491782 -o /tmp/input.3:130994975-1354917820FkeoI.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdout_ZR1n9.log / /tmp/stderrd8oeMY.log
2019-09-10 15:30:01,824 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:01,825 ERROR    Aborted (core dumped)
2019-09-10 15:30:01,825 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:01,825 ERROR    ------------------------------------------------------------
2019-09-10 15:30:01,826 ERROR    Traceback (most recent call last):
2019-09-10 15:30:01,826 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:01,827 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:01,827 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:01,828 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:01,828 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:01,828 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:01,829 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:130994975-135491782 -o /tmp/input.3:130994975-1354917820FkeoI.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:01,829 ERROR    ------------------------------------------------------------
2019-09-10 15:30:07,729 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 21:35624759-37021956 -o /tmp/input.21:35624759-37021956oLRvHY.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutmCBtYP.log / /tmp/stderr8iCZbH.log
2019-09-10 15:30:07,729 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:07,730 ERROR    Aborted (core dumped)
2019-09-10 15:30:07,730 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:07,730 ERROR    ------------------------------------------------------------
2019-09-10 15:30:07,730 ERROR    Traceback (most recent call last):
2019-09-10 15:30:07,730 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:07,730 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:07,730 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:07,730 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:07,731 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:07,731 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:07,731 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 21:35624759-37021956 -o /tmp/input.21:35624759-37021956oLRvHY.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:07,731 ERROR    ------------------------------------------------------------
2019-09-10 15:30:08,911 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:10807132-16504983 -o /tmp/input.3:10807132-165049833EYGvH.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutswnASQ.log / /tmp/stderrHUZfQc.log
2019-09-10 15:30:08,911 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:08,911 ERROR    Aborted (core dumped)
2019-09-10 15:30:08,911 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:08,912 ERROR    ------------------------------------------------------------
2019-09-10 15:30:08,912 ERROR    Traceback (most recent call last):
2019-09-10 15:30:08,912 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:08,912 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:08,912 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:08,912 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:08,912 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:08,913 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:08,913 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:10807132-16504983 -o /tmp/input.3:10807132-165049833EYGvH.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:08,913 ERROR    ------------------------------------------------------------
2019-09-10 15:30:16,680 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:36998800-44158047 -o /tmp/input.3:36998800-44158047hezEhG.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutYemyKC.log / /tmp/stderrvtkR9y.log
2019-09-10 15:30:16,681 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:16,681 ERROR    Aborted (core dumped)
2019-09-10 15:30:16,682 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:16,682 ERROR    ------------------------------------------------------------
2019-09-10 15:30:16,683 ERROR    Traceback (most recent call last):
2019-09-10 15:30:16,683 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:16,684 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:16,684 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:16,684 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:16,685 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:16,685 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:16,686 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:36998800-44158047 -o /tmp/input.3:36998800-44158047hezEhG.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:16,686 ERROR    ------------------------------------------------------------
2019-09-10 15:30:20,948 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 6:74275294-78208081 -o /tmp/input.6:74275294-782080816Gpqoh.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdout5d_vb7.log / /tmp/stderrw_vatl.log
2019-09-10 15:30:20,949 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:20,950 ERROR    Aborted (core dumped)
2019-09-10 15:30:20,950 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:20,950 ERROR    ------------------------------------------------------------
2019-09-10 15:30:20,951 ERROR    Traceback (most recent call last):
2019-09-10 15:30:20,952 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:20,952 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:20,952 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:20,953 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:20,953 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:20,953 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:20,954 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 6:74275294-78208081 -o /tmp/input.6:74275294-782080816Gpqoh.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:20,954 ERROR    ------------------------------------------------------------
2019-09-10 15:30:23,071 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:124713022-130994974 -o /tmp/input.3:124713022-130994974dlXrD0.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutIjqIqq.log / /tmp/stderrns2AJM.log
2019-09-10 15:30:23,072 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:23,073 ERROR    Aborted (core dumped)
2019-09-10 15:30:23,073 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:23,074 ERROR    ------------------------------------------------------------
2019-09-10 15:30:23,074 ERROR    Traceback (most recent call last):
2019-09-10 15:30:23,074 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:23,075 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:23,075 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:23,076 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:23,076 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:23,077 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:23,077 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 3:124713022-130994974 -o /tmp/input.3:124713022-130994974dlXrD0.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:23,077 ERROR    ------------------------------------------------------------
2019-09-10 15:30:34,434 ERROR    Preprocess command preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 8:11148861-15121461 -o /tmp/input.8:11148861-15121461mtpYm1.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta failed. Outputs are here /tmp/stdoutqPneyr.log / /tmp/stderrtoTviD.log
2019-09-10 15:30:34,435 ERROR    preprocess: vcf.c:3472: bcf_update_format: Assertion `!fmt->p_free' failed.
2019-09-10 15:30:34,435 ERROR    Aborted (core dumped)
2019-09-10 15:30:34,436 ERROR    Exception when running <function preprocessWrapper at 0x7f35bab28140>:
2019-09-10 15:30:34,436 ERROR    ------------------------------------------------------------
2019-09-10 15:30:34,436 ERROR    Traceback (most recent call last):
2019-09-10 15:30:34,437 ERROR      File "/opt/hap.py/lib/python27/Tools/parallel.py", line 72, in parMapper
2019-09-10 15:30:34,437 ERROR        return arg[1]['fun'](arg[0], *arg[1]['args'], **arg[1]['kwargs'])
2019-09-10 15:30:34,438 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 67, in preprocessWrapper
2019-09-10 15:30:34,438 ERROR        subprocess.check_call(to_run, shell=True, stdout=tfo, stderr=tfe)
2019-09-10 15:30:34,438 ERROR      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-09-10 15:30:34,439 ERROR        raise CalledProcessError(retcode, cmd)
2019-09-10 15:30:34,439 ERROR    CalledProcessError: Command 'preprocess /tmp/tmpxX3Rhw.vcf.gz:* -l 8:11148861-15121461 -o /tmp/input.8:11148861-15121461mtpYm1.prep.vcf.gz -V 1 -L 1 -r /outputs/ref/human_g1k_v37/human_g1k_v37.fasta' returned non-zero exit status 134
2019-09-10 15:30:34,439 ERROR    ------------------------------------------------------------
2019-09-10 15:30:43,487 ERROR    One of the preprocess jobs failed
2019-09-10 15:30:43,487 ERROR    Traceback (most recent call last):
2019-09-10 15:30:43,487 ERROR      File "/opt/hap.py/bin/hap.py", line 508, in <module>
2019-09-10 15:30:43,488 ERROR        main()
2019-09-10 15:30:43,488 ERROR      File "/opt/hap.py/bin/hap.py", line 363, in main
2019-09-10 15:30:43,488 ERROR        "QUERY")
2019-09-10 15:30:43,488 ERROR      File "/opt/hap.py/bin/pre.py", line 203, in preprocess
2019-09-10 15:30:43,488 ERROR        haploid_x=gender == "male")
2019-09-10 15:30:43,488 ERROR      File "/opt/hap.py/lib/python27/Haplo/partialcredit.py", line 214, in partialCredit
2019-09-10 15:30:43,488 ERROR        raise Exception("One of the preprocess jobs failed")
2019-09-10 15:30:43,488 ERROR    Exception: One of the preprocess jobs failed
root@86876e01e030:/outputs#
```
Could you help me, please?

**Comment by adRn-s** [comment]
I've found this error too:

` preprocess: vcf.c:3496: bcf_update_format: Assertion `!fmt->p_free' failed.`

I ran:

`hap.py {input.baselin} {input.callset} --roc QUAL \                                                                                                               
               -T {input.targets} -r {input.ref} -o {output}/i`

(parameter values are in `{}` because this was part of a Snakefile)

I guess the tool is still in beta or alpha state?

**Comment by Lenbok** [comment]
You can always try running RTG vcfeval directly if you don't need stratification.

**Comment by ruolin** [comment]
Same issue here. Any updates?

**Comment by ruolin** [comment]
I found out a multiple-sample vcf will give this error.

**Comment by adRn-s** [comment]
> I found out a multiple-sample vcf will give this error.

Same here.

**Comment by netwon123** [comment]
add -T will cause this problem, but i don't know how to solve it

**Comment by vibaotram** [comment]
I got the same error. But it has been solved by keeping only GT and removing all the other fields in FORMAT column.
